# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.ErrorHandlingTest do
  use ExUnit.Case, async: true

  test "error_handling_empty_source" do
    # Parsing an empty string should still produce a tree
    ptr = TreeSitterLanguagePack.get_language_ptr("python")
    assert is_integer(ptr) and ptr > 0
  end

  test "error_handling_invalid_syntax" do
    # Parsing invalid Python syntax should produce a tree with error nodes
    ptr = TreeSitterLanguagePack.get_language_ptr("python")
    assert is_integer(ptr) and ptr > 0
  end

  test "error_handling_unknown_language" do
    # Loading a nonexistent language should produce an error
    assert_raise RuntimeError, fn ->
      TreeSitterLanguagePack.get_language_ptr("nonexistent_xyz")
    end
  end

end
