# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.MetadataTest do
  use ExUnit.Case, async: true

  @tag :skip_unless_go
  test "go_function_metadata" do
    # Intel: extract structure from Go function definition
    unless TreeSitterLanguagePack.has_language("go") do
      IO.puts("Skipping: language 'go' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n",
          "go"
        )

      assert metadata["language"] == "go"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Function" end)
      assert length(metadata["imports"]) >= 1
      assert metadata["metrics"]["total_lines"] >= 7
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_javascript
  test "javascript_multi_import_metadata" do
    # Intel: detect multiple imports and function in JavaScript
    unless TreeSitterLanguagePack.has_language("javascript") do
      IO.puts("Skipping: language 'javascript' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n",
          "javascript"
        )

      assert metadata["language"] == "javascript"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Function" end)
      assert length(metadata["imports"]) >= 2
      assert metadata["metrics"]["total_lines"] >= 6
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_javascript
  test "meta_javascript_exports_detail" do
    # JavaScript with exports, verify export count
    unless TreeSitterLanguagePack.has_language("javascript") do
      IO.puts("Skipping: language 'javascript' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n",
          "javascript"
        )

      assert metadata["language"] == "javascript"
      assert length(metadata["exports"]) >= 1
    end
  end

  @tag :skip_unless_python
  test "meta_python_comments" do
    # Python with comments, verify comment count
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "\# This is a comment\n\# Another comment\ndef hello():\n    \# inline comment\n    pass\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert length(metadata["comments"]) >= 1
    end
  end

  @tag :skip_unless_python
  test "meta_python_imports_detail" do
    # Python with multiple imports, verify imports contain specific source
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert length(metadata["imports"]) >= 2
      assert Enum.any?(metadata["imports"], fn i -> String.contains?(i["source"] || "", "os") end)
    end
  end

  @tag :skip_unless_python
  test "meta_python_metrics_detail" do
    # Python code with metrics assertions
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "\# module docstring\nimport os\n\ndef hello():\n    \# greeting\n    print('hello')\n\ndef world():\n    print('world')\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert metadata["metrics"]["code_lines"] >= 4
      assert metadata["metrics"]["comment_lines"] >= 1
      assert metadata["metrics"]["max_depth"] >= 1
    end
  end

  @tag :skip_unless_rust
  test "meta_rust_structure_name" do
    # Rust struct with name, verify structure name contains value
    unless TreeSitterLanguagePack.has_language("rust") do
      IO.puts("Skipping: language 'rust' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n",
          "rust"
        )

      assert metadata["language"] == "rust"
      assert length(metadata["structure"]) >= 1

      assert Enum.any?(metadata["structure"], fn s ->
               s["name"] != nil and String.contains?(s["name"], "MyConfig")
             end)
    end
  end

  @tag :skip_unless_python
  test "python_chunking_metadata" do
    # Intel: chunk multi-function Python source into multiple pieces
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      result =
        TreeSitterLanguagePack.process(
          "def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n",
          "python",
          30
        )

      metadata = result["metadata"]
      chunks = result["chunks"]
      assert metadata["language"] == "python"
      assert metadata["metrics"]["total_lines"] >= 8
      assert length(chunks) >= 2
    end
  end

  @tag :skip_unless_python
  test "python_class_with_methods_metadata" do
    # Intel: extract nested structure from Python class with methods
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Class" end)
      assert metadata["metrics"]["total_lines"] >= 6
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_python
  test "python_function_metadata" do
    # Intel: extract structure from Python function definition
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "def greet(name):\n    return f'Hello, {name}!'\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Function" end)
      assert metadata["metrics"]["total_lines"] >= 2
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_python
  test "python_malformed_code_metadata" do
    # Intel: detect diagnostics in malformed Python code
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata = TreeSitterLanguagePack.analyze("def broken(\n    return\nclass", "python")
      assert metadata["language"] == "python"
      assert length(metadata["diagnostics"]) > 0
    end
  end

  @tag :skip_unless_python
  test "python_multi_import_metadata" do
    # Intel: detect multiple Python imports
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
          "python"
        )

      assert metadata["language"] == "python"
      assert length(metadata["structure"]) >= 1
      assert length(metadata["imports"]) >= 3
      assert metadata["metrics"]["total_lines"] >= 5
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_rust
  test "rust_chunking_metadata" do
    # Intel: chunk multi-function Rust source into pieces
    unless TreeSitterLanguagePack.has_language("rust") do
      IO.puts("Skipping: language 'rust' not available")
    else
      result =
        TreeSitterLanguagePack.process(
          "fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n",
          "rust",
          30
        )

      metadata = result["metadata"]
      chunks = result["chunks"]
      assert metadata["language"] == "rust"
      assert metadata["metrics"]["total_lines"] >= 7
      assert length(chunks) >= 2
    end
  end

  @tag :skip_unless_rust
  test "rust_function_metadata" do
    # Intel: extract structure from Rust function definition
    unless TreeSitterLanguagePack.has_language("rust") do
      IO.puts("Skipping: language 'rust' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")

      assert metadata["language"] == "rust"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Function" end)
      assert metadata["metrics"]["total_lines"] >= 3
      assert metadata["metrics"]["error_count"] == 0
    end
  end

  @tag :skip_unless_typescript
  test "typescript_function_metadata" do
    # Intel: extract structure from TypeScript function
    unless TreeSitterLanguagePack.has_language("typescript") do
      IO.puts("Skipping: language 'typescript' not available")
    else
      metadata =
        TreeSitterLanguagePack.analyze(
          "import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n",
          "typescript"
        )

      assert metadata["language"] == "typescript"
      assert length(metadata["structure"]) >= 1
      assert Enum.any?(metadata["structure"], fn s -> s["kind"] == "Function" end)
      assert length(metadata["imports"]) >= 1
      assert metadata["metrics"]["total_lines"] >= 5
      assert metadata["metrics"]["error_count"] == 0
    end
  end
end
