# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.ParsingTest do
  use ExUnit.Case, async: true

  test "parsing_go_function" do
    # Parse a Go function declaration and assert node type
    ptr = TreeSitterLanguagePack.get_language_ptr("go")
    assert is_integer(ptr) and ptr > 0
  end

  test "parsing_html_element" do
    # Parse an HTML element and assert node type
    ptr = TreeSitterLanguagePack.get_language_ptr("html")
    assert is_integer(ptr) and ptr > 0
  end

  test "parsing_javascript_variable" do
    # Parse a JavaScript variable declaration and assert node type
    ptr = TreeSitterLanguagePack.get_language_ptr("javascript")
    assert is_integer(ptr) and ptr > 0
  end

  test "parsing_python_function" do
    # Parse a Python function definition and assert node type
    ptr = TreeSitterLanguagePack.get_language_ptr("python")
    assert is_integer(ptr) and ptr > 0
  end

  test "parsing_rust_function" do
    # Parse a Rust function definition and assert node type
    ptr = TreeSitterLanguagePack.get_language_ptr("rust")
    assert is_integer(ptr) and ptr > 0
  end

end
