# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.SmokeTest do
  use ExUnit.Case, async: true

  test "smoke_c" do
    # Smoke test: load c and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("c")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_cpp" do
    # Smoke test: load cpp and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("cpp")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_go" do
    # Smoke test: load go and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("go")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_html" do
    # Smoke test: load html and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("html")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_java" do
    # Smoke test: load java and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("java")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_javascript" do
    # Smoke test: load javascript and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("javascript")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_python" do
    # Smoke test: load python and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("python")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_ruby" do
    # Smoke test: load ruby and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("ruby")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_rust" do
    # Smoke test: load rust and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("rust")
    assert is_integer(ptr) and ptr > 0
  end

  test "smoke_typescript" do
    # Smoke test: load typescript and parse a simple snippet
    ptr = TreeSitterLanguagePack.get_language_ptr("typescript")
    assert is_integer(ptr) and ptr > 0
  end

end
