# Code generated by e2e-generator. DO NOT EDIT.

defmodule E2eTests.TreeInspectionTest do
  use ExUnit.Case, async: true

  @tag :skip_unless_python
  test "tree_error_count_broken" do
    # Parse broken Python code and verify error count >= 1
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      tree = TreeSitterLanguagePack.parse_string("python", "def (broken syntax @@@ !!!")
      assert is_reference(tree), "Parse tree should be a reference"
      assert TreeSitterLanguagePack.tree_has_error_nodes(tree), "Tree should contain error nodes"
    end
  end

  @tag :skip_unless_python
  test "tree_error_count_valid" do
    # Parse valid Python code and verify zero error count
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      tree = TreeSitterLanguagePack.parse_string("python", "x = 1\ny = 2\n")
      assert is_reference(tree), "Parse tree should be a reference"
      refute TreeSitterLanguagePack.tree_has_error_nodes(tree)
    end
  end

  @tag :skip_unless_python
  test "tree_find_nodes_two_functions" do
    # Parse Python with 2 functions and verify find_nodes_by_type count
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      tree =
        TreeSitterLanguagePack.parse_string(
          "python",
          "def foo():\n    pass\n\ndef bar():\n    pass\n"
        )

      assert is_reference(tree), "Parse tree should be a reference"
      nodes = TreeSitterLanguagePack.tree_find_nodes_by_type(tree, "function_definition")
      assert length(nodes) >= 2
    end
  end

  @tag :skip_unless_python
  test "tree_named_children_class_and_function" do
    # Parse Python with class and function, verify named children count
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      tree =
        TreeSitterLanguagePack.parse_string(
          "python",
          "class Foo:\n    pass\n\ndef bar():\n    pass\n"
        )

      assert is_reference(tree), "Parse tree should be a reference"
      children = TreeSitterLanguagePack.tree_named_children_info(tree)
      assert length(children) >= 2
    end
  end

  @tag :skip_unless_python
  test "tree_root_node_info_python" do
    # Parse Python source and verify root node info
    unless TreeSitterLanguagePack.has_language("python") do
      IO.puts("Skipping: language 'python' not available")
    else
      tree = TreeSitterLanguagePack.parse_string("python", "def hello():\n    pass\n")
      assert is_reference(tree), "Parse tree should be a reference"
      root_type = TreeSitterLanguagePack.tree_root_node_type(tree)
      assert root_type == "module"
    end
  end
end
