// Code generated by e2e-generator. DO NOT EDIT.

package io.github.treesitter.languagepack.e2e;

import static org.junit.jupiter.api.Assertions.*;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import org.junit.jupiter.api.Test;

class MetadataTest {

  private static final Gson GSON = new Gson();

  @Test
  void go_function_metadata() {
    // Intel: extract structure from Go function definition
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("go"), "Language 'go' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n",
              "go");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("go", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Function")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Function' kind node");
      assertTrue(
          metadata.getAsJsonArray("imports").size() >= 1, "Should have at least 1 import(s)");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 7, "Should have at least 7 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void javascript_multi_import_metadata() {
    // Intel: detect multiple imports and function in JavaScript
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("javascript"), "Language 'javascript' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "import fs from 'fs';\n"
                  + "import path from 'path';\n\n"
                  + "function process(input) {\n"
                  + "    return input.trim();\n"
                  + "}\n",
              "javascript");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("javascript", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Function")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Function' kind node");
      assertTrue(
          metadata.getAsJsonArray("imports").size() >= 2, "Should have at least 2 import(s)");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 6, "Should have at least 6 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void meta_javascript_exports_detail() {
    // JavaScript with exports, verify export count
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("javascript"), "Language 'javascript' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "export function greet(name) {\n"
                  + "  return `Hello ${name}`;\n"
                  + "}\n\n"
                  + "export const VERSION = '1.0';\n",
              "javascript");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("javascript", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("exports").size() >= 1, "Should have at least 1 export(s)");
    }
  }

  @Test
  void meta_python_comments() {
    // Python with comments, verify comment count
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "# This is a comment\n"
                  + "# Another comment\n"
                  + "def hello():\n"
                  + "    # inline comment\n"
                  + "    pass\n",
              "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("comments").size() >= 1, "Should have at least 1 comment(s)");
    }
  }

  @Test
  void meta_python_imports_detail() {
    // Python with multiple imports, verify imports contain specific source
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
              "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("imports").size() >= 2, "Should have at least 2 import(s)");
      boolean foundImportSource = false;
      for (var imp : metadata.getAsJsonArray("imports")) {
        if (imp.getAsJsonObject().get("source").getAsString().contains("os")) {
          foundImportSource = true;
          break;
        }
      }
      assertTrue(foundImportSource, "imports should contain source 'os'");
    }
  }

  @Test
  void meta_python_metrics_detail() {
    // Python code with metrics assertions
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "# module docstring\n"
                  + "import os\n\n"
                  + "def hello():\n"
                  + "    # greeting\n"
                  + "    print('hello')\n\n"
                  + "def world():\n"
                  + "    print('world')\n",
              "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(metrics.get("code_lines").getAsInt() >= 4, "Should have at least 4 code line(s)");
      assertTrue(
          metrics.get("comment_lines").getAsInt() >= 1, "Should have at least 1 comment line(s)");
      assertTrue(metrics.get("max_depth").getAsInt() >= 1, "Expected max_depth >= 1");
    }
  }

  @Test
  void meta_rust_structure_name() {
    // Rust struct with name, verify structure name contains value
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("rust"), "Language 'rust' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "pub struct MyConfig {\n"
                  + "    pub name: String,\n"
                  + "    pub value: i32,\n"
                  + "}\n\n"
                  + "impl MyConfig {\n"
                  + "    pub fn new() -> Self {\n"
                  + "        Self { name: String::new(), value: 0 }\n"
                  + "    }\n"
                  + "}\n",
              "rust");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("rust", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundStructureName = false;
      for (var s : metadata.getAsJsonArray("structure")) {
        if (s.getAsJsonObject().get("name").getAsString().contains("MyConfig")) {
          foundStructureName = true;
          break;
        }
      }
      assertTrue(
          foundStructureName, "structure should contain an item with name containing 'MyConfig'");
    }
  }

  @Test
  void python_chunking_metadata() {
    // Intel: chunk multi-function Python source into multiple pieces
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.process(
              "def alpha():\n"
                  + "    pass\n\n"
                  + "def beta():\n"
                  + "    pass\n\n"
                  + "def gamma():\n"
                  + "    pass\n\n"
                  + "def delta():\n"
                  + "    pass\n",
              "python",
              30);
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      JsonArray chunks = metadata.getAsJsonArray("chunks");
      assertTrue(chunks.size() >= 2, "Should have at least 2 chunk(s), got " + chunks.size());
      metadata = metadata.getAsJsonObject("metadata");
      assertEquals("python", metadata.get("language").getAsString());
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 8, "Should have at least 8 total line(s)");
    }
  }

  @Test
  void python_class_with_methods_metadata() {
    // Intel: extract nested structure from Python class with methods
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "class Calculator:\n"
                  + "    def add(self, a, b):\n"
                  + "        return a + b\n\n"
                  + "    def subtract(self, a, b):\n"
                  + "        return a - b\n",
              "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Class")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Class' kind node");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 6, "Should have at least 6 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void python_function_metadata() {
    // Intel: extract structure from Python function definition
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze("def greet(name):\n    return f'Hello, {name}!'\n", "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Function")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Function' kind node");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 2, "Should have at least 2 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void python_malformed_code_metadata() {
    // Intel: detect diagnostics in malformed Python code
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson = registry.analyze("def broken(\n    return\nclass", "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertFalse(
          metadata.getAsJsonArray("diagnostics").isEmpty(), "Diagnostics should not be empty");
    }
  }

  @Test
  void python_multi_import_metadata() {
    // Intel: detect multiple Python imports
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("python"), "Language 'python' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
              "python");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("python", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      assertTrue(
          metadata.getAsJsonArray("imports").size() >= 3, "Should have at least 3 import(s)");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 5, "Should have at least 5 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void rust_chunking_metadata() {
    // Intel: chunk multi-function Rust source into pieces
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("rust"), "Language 'rust' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.process(
              "fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", "rust", 30);
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      JsonArray chunks = metadata.getAsJsonArray("chunks");
      assertTrue(chunks.size() >= 2, "Should have at least 2 chunk(s), got " + chunks.size());
      metadata = metadata.getAsJsonObject("metadata");
      assertEquals("rust", metadata.get("language").getAsString());
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 7, "Should have at least 7 total line(s)");
    }
  }

  @Test
  void rust_function_metadata() {
    // Intel: extract structure from Rust function definition
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("rust"), "Language 'rust' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("rust", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Function")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Function' kind node");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 3, "Should have at least 3 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }

  @Test
  void typescript_function_metadata() {
    // Intel: extract structure from TypeScript function
    try (var registry = Helpers.createRegistry()) {
      org.junit.jupiter.api.Assumptions.assumeTrue(
          registry.hasLanguage("typescript"), "Language 'typescript' not available");
    }
    try (var registry = Helpers.createRegistry()) {
      String resultJson =
          registry.analyze(
              "import { readFile } from 'fs';\n\n"
                  + "function greet(name: string): string {\n"
                  + "    return `Hello, ${name}!`;\n"
                  + "}\n",
              "typescript");
      JsonObject metadata = GSON.fromJson(resultJson, JsonObject.class);
      assertEquals("typescript", metadata.get("language").getAsString());
      assertTrue(
          metadata.getAsJsonArray("structure").size() >= 1, "Should have at least 1 structure(s)");
      boolean foundKind = false;
      for (var elem : metadata.getAsJsonArray("structure")) {
        if (elem.getAsJsonObject().get("kind").getAsString().equals("Function")) {
          foundKind = true;
          break;
        }
      }
      assertTrue(foundKind, "Structure should contain a 'Function' kind node");
      assertTrue(
          metadata.getAsJsonArray("imports").size() >= 1, "Should have at least 1 import(s)");
      JsonObject metrics = metadata.getAsJsonObject("metrics");
      assertTrue(
          metrics.get("total_lines").getAsInt() >= 5, "Should have at least 5 total line(s)");
      assertEquals(0, metrics.get("error_count").getAsInt(), "Expected error_count 0");
    }
  }
}
