// Code generated by e2e-generator. DO NOT EDIT.

package io.github.treesitter.languagepack.e2e;

import static org.junit.jupiter.api.Assertions.*;

import io.github.treesitter.languagepack.TsPackRegistry;
import org.junit.jupiter.api.Test;

class SmokeTest {

    @Test
    void smoke_c() {
        // Smoke test: load c and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("c");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_cpp() {
        // Smoke test: load cpp and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("cpp");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_go() {
        // Smoke test: load go and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("go");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_html() {
        // Smoke test: load html and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("html");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_java() {
        // Smoke test: load java and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("java");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_javascript() {
        // Smoke test: load javascript and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("javascript");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_python() {
        // Smoke test: load python and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("python");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_ruby() {
        // Smoke test: load ruby and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("ruby");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_rust() {
        // Smoke test: load rust and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("rust");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

    @Test
    void smoke_typescript() {
        // Smoke test: load typescript and parse a simple snippet
        try (var registry = Helpers.createRegistry()) {
            var langPtr = registry.getLanguage("typescript");
            assertNotNull(langPtr, "Language pointer should not be null");
        }
    }

}
