// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** Metadata for a code chunk. */
public record ChunkInfo(
    String language,
    @SerializedName("chunk_index") int chunkIndex,
    @SerializedName("total_chunks") int totalChunks,
    @SerializedName("node_types") List<String> nodeTypes,
    @SerializedName("context_path") List<String> contextPath,
    @SerializedName("symbols_defined") List<String> symbolsDefined,
    List<CommentInfo> comments,
    List<DocstringInfo> docstrings,
    @SerializedName("has_error_nodes") boolean hasErrorNodes) {}
