// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** A chunk of source code with rich metadata. */
public record CodeChunk(
    String content,
    @SerializedName("start_byte") int startByte,
    @SerializedName("end_byte") int endByte,
    @SerializedName("start_line") int startLine,
    @SerializedName("end_line") int endLine,
    ChunkInfo metadata) {}
