// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** A comment extracted from source code. */
public record CommentInfo(
    String text,
    String kind,
    Span span,
    @SerializedName("associated_node") String associatedNode) {}
