// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

/** A diagnostic (syntax error, missing node) from parsing. */
public record Diagnostic(String message, String severity, Span span) {}
