// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

/** A section within a docstring. */
public record DocSection(String kind, String name, String description) {}
