// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** A docstring extracted from source code. */
public record DocstringInfo(
    String text,
    String format,
    Span span,
    @SerializedName("associated_item") String associatedItem,
    @SerializedName("parsed_sections") List<DocSection> parsedSections) {}
