// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

/** An export statement extracted from source code. */
public record ExportInfo(String name, String kind, Span span) {}
