// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** Aggregate metrics for a source file. */
public record FileMetrics(
    @SerializedName("total_lines") int totalLines,
    @SerializedName("code_lines") int codeLines,
    @SerializedName("comment_lines") int commentLines,
    @SerializedName("blank_lines") int blankLines,
    @SerializedName("total_bytes") int totalBytes,
    @SerializedName("node_count") int nodeCount,
    @SerializedName("error_count") int errorCount,
    @SerializedName("max_depth") int maxDepth) {}
