// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import java.util.List;

/** Complete metadata extracted from a source file. */
public record FileMetadata(
    String language,
    FileMetrics metrics,
    List<StructureItem> structure,
    List<ImportInfo> imports,
    List<ExportInfo> exports,
    List<CommentInfo> comments,
    List<DocstringInfo> docstrings,
    List<SymbolInfo> symbols,
    List<Diagnostic> diagnostics) {}
