// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** An import statement extracted from source code. */
public record ImportInfo(
    String source,
    List<String> items,
    String alias,
    @SerializedName("is_wildcard") boolean isWildcard,
    Span span) {}
