// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** Information about a tree-sitter syntax node. */
public record NodeInfo(
    String kind,
    @SerializedName("is_named") boolean isNamed,
    @SerializedName("start_byte") int startByte,
    @SerializedName("end_byte") int endByte,
    @SerializedName("start_row") int startRow,
    @SerializedName("start_column") int startColumn,
    @SerializedName("end_row") int endRow,
    @SerializedName("end_column") int endColumn,
    @SerializedName("named_child_count") int namedChildCount,
    @SerializedName("is_error") boolean isError,
    @SerializedName("is_missing") boolean isMissing) {}
