// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import java.util.List;

/** Result of process containing metadata and chunks. */
public record ProcessResult(FileMetadata metadata, List<CodeChunk> chunks) {}
