// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** Byte and line/column range in source code. */
public record Span(
    @SerializedName("start_byte") int startByte,
    @SerializedName("end_byte") int endByte,
    @SerializedName("start_line") int startLine,
    @SerializedName("start_column") int startColumn,
    @SerializedName("end_line") int endLine,
    @SerializedName("end_column") int endColumn) {}
