// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** A structural element in source code (function, class, struct, etc.). */
public record StructureItem(
    String kind,
    String name,
    String visibility,
    Span span,
    List<StructureItem> children,
    List<String> decorators,
    @SerializedName("doc_comment") String docComment,
    String signature,
    @SerializedName("body_span") Span bodySpan) {}
