// Code generated by tree-sitter-language-pack. DO NOT EDIT.
package io.github.treesitter.languagepack;

import com.google.gson.annotations.SerializedName;

/** A symbol (variable, function, type) extracted from source code. */
public record SymbolInfo(
    String name,
    String kind,
    Span span,
    @SerializedName("type_annotation") String typeAnnotation,
    String doc) {}
