// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn tree_error_count_broken() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse broken Python code and verify error count >= 1
    let mut parser = ts_pack_core::get_parser("python").expect("Failed to get parser for 'python'");
    let tree = parser.parse("def (broken syntax @@@ !!!", None);
    assert!(tree.is_some(), "Parse tree should not be None");
    let tree = tree.unwrap();
    let root = tree.root_node();
    assert!(e2e_tests::tree_has_error_nodes(root), "Tree should contain error nodes");
}

#[test]
fn tree_error_count_valid() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse valid Python code and verify zero error count
    let tree = ts_pack_core::parse_string("python", b"x = 1\ny = 2\n").expect("parse failed");
    assert_eq!(
        ts_pack_core::tree_error_count(&tree),
        0,
        "Expected tree_error_count == 0"
    );
}

#[test]
fn tree_find_nodes_two_functions() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse Python with 2 functions and verify find_nodes_by_type count
    let tree =
        ts_pack_core::parse_string("python", b"def foo():\n    pass\n\ndef bar():\n    pass\n").expect("parse failed");
    let nodes = ts_pack_core::find_nodes_by_type(&tree, "function_definition");
    assert!(
        nodes.len() >= 2,
        "Expected at least 2 'function_definition' node(s), got {}",
        nodes.len()
    );
}

#[test]
fn tree_named_children_class_and_function() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse Python with class and function, verify named children count
    let tree =
        ts_pack_core::parse_string("python", b"class Foo:\n    pass\n\ndef bar():\n    pass\n").expect("parse failed");
    let children = ts_pack_core::named_children_info(&tree);
    assert!(
        children.len() >= 2,
        "Expected at least 2 named child(ren), got {}",
        children.len()
    );
}

#[test]
fn tree_root_node_info_python() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Parse Python source and verify root node info
    let tree = ts_pack_core::parse_string("python", b"def hello():\n    pass\n").expect("parse failed");
    let root_info = ts_pack_core::root_node_info(&tree);
    assert_eq!(root_info.kind, "module", "Root node type mismatch");
}
