// Code generated by e2e-generator. DO NOT EDIT.
#![allow(clippy::too_many_lines)]

#[test]
fn go_function_metadata() {
    if !ts_pack_core::has_language("go") {
        eprintln!("Skipping: language 'go' not available");
        return;
    }
    // Intel: extract structure from Go function definition
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze(
            "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n",
            "go",
        )
        .expect("analyze failed");
    assert_eq!(metadata.language, "go", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Function),
        "Structure should contain a 'Function' item"
    );
    assert!(
        metadata.imports.len() >= 1,
        "Expected at least 1 import(s), got {}",
        metadata.imports.len()
    );
    assert!(
        metadata.metrics.total_lines >= 7,
        "Expected at least 7 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn javascript_multi_import_metadata() {
    if !ts_pack_core::has_language("javascript") {
        eprintln!("Skipping: language 'javascript' not available");
        return;
    }
    // Intel: detect multiple imports and function in JavaScript
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry.analyze("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", "javascript").expect("analyze failed");
    assert_eq!(metadata.language, "javascript", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Function),
        "Structure should contain a 'Function' item"
    );
    assert!(
        metadata.imports.len() >= 2,
        "Expected at least 2 import(s), got {}",
        metadata.imports.len()
    );
    assert!(
        metadata.metrics.total_lines >= 6,
        "Expected at least 6 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn meta_javascript_exports_detail() {
    if !ts_pack_core::has_language("javascript") {
        eprintln!("Skipping: language 'javascript' not available");
        return;
    }
    // JavaScript with exports, verify export count
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze(
            "export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n",
            "javascript",
        )
        .expect("analyze failed");
    assert_eq!(metadata.language, "javascript", "metadata.language mismatch");
    assert!(
        metadata.exports.len() >= 1,
        "Expected at least 1 export(s), got {}",
        metadata.exports.len()
    );
}

#[test]
fn meta_python_comments() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Python with comments, verify comment count
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze(
            "# This is a comment\n# Another comment\ndef hello():\n    # inline comment\n    pass\n",
            "python",
        )
        .expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.comments.len() >= 1,
        "Expected at least 1 comment(s), got {}",
        metadata.comments.len()
    );
}

#[test]
fn meta_python_imports_detail() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Python with multiple imports, verify imports contain specific source
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze(
            "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
            "python",
        )
        .expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.imports.len() >= 2,
        "Expected at least 2 import(s), got {}",
        metadata.imports.len()
    );
    assert!(
        metadata.imports.iter().any(|i| i.source.contains("os")),
        "imports should contain one with source containing 'os'"
    );
}

#[test]
fn meta_python_metrics_detail() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Python code with metrics assertions
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry.analyze("# module docstring\nimport os\n\ndef hello():\n    # greeting\n    print('hello')\n\ndef world():\n    print('world')\n", "python").expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.metrics.code_lines >= 4,
        "Expected at least 4 code line(s), got {}",
        metadata.metrics.code_lines
    );
    assert!(
        metadata.metrics.comment_lines >= 1,
        "Expected at least 1 comment line(s), got {}",
        metadata.metrics.comment_lines
    );
    assert!(
        metadata.metrics.max_depth >= 1,
        "Expected max_depth >= 1, got {}",
        metadata.metrics.max_depth
    );
}

#[test]
fn meta_rust_structure_name() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Rust struct with name, verify structure name contains value
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry.analyze("pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n", "rust").expect("analyze failed");
    assert_eq!(metadata.language, "rust", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.name.as_deref().is_some_and(|n| n.contains("MyConfig"))),
        "Structure should contain an item with name containing 'MyConfig'"
    );
}

#[test]
fn python_chunking_metadata() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: chunk multi-function Python source into multiple pieces
    let registry = ts_pack_core::LanguageRegistry::new();
    let (metadata, chunks) = registry
        .process(
            "def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n",
            "python",
            30,
        )
        .expect("process failed");
    assert!(chunks.len() >= 2, "Expected at least 2 chunk(s), got {}", chunks.len());
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.metrics.total_lines >= 8,
        "Expected at least 8 total line(s), got {}",
        metadata.metrics.total_lines
    );
}

#[test]
fn python_class_with_methods_metadata() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: extract nested structure from Python class with methods
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry.analyze("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", "python").expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Class),
        "Structure should contain a 'Class' item"
    );
    assert!(
        metadata.metrics.total_lines >= 6,
        "Expected at least 6 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn python_function_metadata() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: extract structure from Python function definition
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze("def greet(name):\n    return f'Hello, {name}!'\n", "python")
        .expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Function),
        "Structure should contain a 'Function' item"
    );
    assert!(
        metadata.metrics.total_lines >= 2,
        "Expected at least 2 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn python_malformed_code_metadata() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: detect diagnostics in malformed Python code
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze("def broken(\n    return\nclass", "python")
        .expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(!metadata.diagnostics.is_empty(), "diagnostics should not be empty");
}

#[test]
fn python_multi_import_metadata() {
    if !ts_pack_core::has_language("python") {
        eprintln!("Skipping: language 'python' not available");
        return;
    }
    // Intel: detect multiple Python imports
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze(
            "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n",
            "python",
        )
        .expect("analyze failed");
    assert_eq!(metadata.language, "python", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata.imports.len() >= 3,
        "Expected at least 3 import(s), got {}",
        metadata.imports.len()
    );
    assert!(
        metadata.metrics.total_lines >= 5,
        "Expected at least 5 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn rust_chunking_metadata() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Intel: chunk multi-function Rust source into pieces
    let registry = ts_pack_core::LanguageRegistry::new();
    let (metadata, chunks) = registry
        .process(
            "fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n",
            "rust",
            30,
        )
        .expect("process failed");
    assert!(chunks.len() >= 2, "Expected at least 2 chunk(s), got {}", chunks.len());
    assert_eq!(metadata.language, "rust", "metadata.language mismatch");
    assert!(
        metadata.metrics.total_lines >= 7,
        "Expected at least 7 total line(s), got {}",
        metadata.metrics.total_lines
    );
}

#[test]
fn rust_function_metadata() {
    if !ts_pack_core::has_language("rust") {
        eprintln!("Skipping: language 'rust' not available");
        return;
    }
    // Intel: extract structure from Rust function definition
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry
        .analyze("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", "rust")
        .expect("analyze failed");
    assert_eq!(metadata.language, "rust", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Function),
        "Structure should contain a 'Function' item"
    );
    assert!(
        metadata.metrics.total_lines >= 3,
        "Expected at least 3 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}

#[test]
fn typescript_function_metadata() {
    if !ts_pack_core::has_language("typescript") {
        eprintln!("Skipping: language 'typescript' not available");
        return;
    }
    // Intel: extract structure from TypeScript function
    let registry = ts_pack_core::LanguageRegistry::new();
    let metadata = registry.analyze("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", "typescript").expect("analyze failed");
    assert_eq!(metadata.language, "typescript", "metadata.language mismatch");
    assert!(
        metadata.structure.len() >= 1,
        "Expected at least 1 structure item(s), got {}",
        metadata.structure.len()
    );
    assert!(
        metadata
            .structure
            .iter()
            .any(|s| s.kind == ts_pack_core::StructureKind::Function),
        "Structure should contain a 'Function' item"
    );
    assert!(
        metadata.imports.len() >= 1,
        "Expected at least 1 import(s), got {}",
        metadata.imports.len()
    );
    assert!(
        metadata.metrics.total_lines >= 5,
        "Expected at least 5 total line(s), got {}",
        metadata.metrics.total_lines
    );
    assert_eq!(
        metadata.metrics.error_count, 0,
        "Expected error_count == 0, got {}",
        metadata.metrics.error_count
    );
}
