// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr } from "@tree-sitter-language-pack/node";

describe("error_handling", () => {
  it("error_handling_empty_source", () => {
    // Parsing an empty string should still produce a tree
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("error_handling_invalid_syntax", () => {
    // Parsing invalid Python syntax should produce a tree with error nodes
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("error_handling_unknown_language", () => {
    // Loading a nonexistent language should produce an error
    expect(() => getLanguagePtr("nonexistent_xyz")).toThrow();
  });

});
