// Code generated by e2e-generator. DO NOT EDIT.
//
// Type declarations for the @tree-sitter-language-pack/node native module.
// These mirror the NAPI-RS generated types from crates/ts-pack-node/src/lib.rs.

declare module "@tree-sitter-language-pack/node" {
  /** Opaque handle to a parsed tree-sitter Tree (NAPI ExternalObject). */
  export interface ExternalObject<T> {
    readonly __brand: T;
  }

  /** Branded tag for tree-sitter Tree handles. */
  interface Tree {
    readonly __tree_sitter_tree: unique symbol;
  }

  /** Opaque tree handle returned by parseString. */
  export type TreeHandle = ExternalObject<Tree>;

  /** Returns an array of all available language names. */
  export function availableLanguages(): string[];

  /** Checks whether a language with the given name is available. */
  export function hasLanguage(name: string): boolean;

  /** Returns the number of available languages. */
  export function languageCount(): number;

  /**
   * Returns the raw TSLanguage pointer for interop with node-tree-sitter.
   * Throws if the language is not found.
   */
  export function getLanguagePtr(name: string): number;

  /**
   * Parse a source string using the named language and return an opaque tree handle.
   * Throws if the language is not found or parsing fails.
   */
  export function parseString(language: string, source: string): TreeHandle;

  /** Get the type name of the root node. */
  export function treeRootNodeType(tree: TreeHandle): string;

  /** Get the number of named children of the root node. */
  export function treeRootChildCount(tree: TreeHandle): number;

  /** Check whether any node in the tree has the given type name. */
  export function treeContainsNodeType(tree: TreeHandle, nodeType: string): boolean;

  /** Check whether the tree contains any ERROR or MISSING nodes. */
  export function treeHasErrorNodes(tree: TreeHandle): boolean;
}
