// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr } from "@kreuzberg/tree-sitter-language-pack";

describe("smoke", () => {
  it("smoke_c", () => {
    // Smoke test: load c and parse a simple snippet
    const ptr = getLanguagePtr("c");
    expect(ptr).toBeTruthy();
  });

  it("smoke_cpp", () => {
    // Smoke test: load cpp and parse a simple snippet
    const ptr = getLanguagePtr("cpp");
    expect(ptr).toBeTruthy();
  });

  it("smoke_go", () => {
    // Smoke test: load go and parse a simple snippet
    const ptr = getLanguagePtr("go");
    expect(ptr).toBeTruthy();
  });

  it("smoke_html", () => {
    // Smoke test: load html and parse a simple snippet
    const ptr = getLanguagePtr("html");
    expect(ptr).toBeTruthy();
  });

  it("smoke_java", () => {
    // Smoke test: load java and parse a simple snippet
    const ptr = getLanguagePtr("java");
    expect(ptr).toBeTruthy();
  });

  it("smoke_javascript", () => {
    // Smoke test: load javascript and parse a simple snippet
    const ptr = getLanguagePtr("javascript");
    expect(ptr).toBeTruthy();
  });

  it("smoke_python", () => {
    // Smoke test: load python and parse a simple snippet
    const ptr = getLanguagePtr("python");
    expect(ptr).toBeTruthy();
  });

  it("smoke_ruby", () => {
    // Smoke test: load ruby and parse a simple snippet
    const ptr = getLanguagePtr("ruby");
    expect(ptr).toBeTruthy();
  });

  it("smoke_rust", () => {
    // Smoke test: load rust and parse a simple snippet
    const ptr = getLanguagePtr("rust");
    expect(ptr).toBeTruthy();
  });

  it("smoke_typescript", () => {
    // Smoke test: load typescript and parse a simple snippet
    const ptr = getLanguagePtr("typescript");
    expect(ptr).toBeTruthy();
  });

});
