// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import { availableLanguages, hasLanguage, getLanguagePtr, parseString, treeRootChildCount, treeContainsNodeType, treeHasErrorNodes, rootNodeInfo, findNodesByType, namedChildrenInfo, analyze, process } from "./helpers";

describe("tree_inspection", () => {
  it("tree_error_count_broken", () => {
    // Parse broken Python code and verify error count >= 1
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const tree = parseString("python", "def (broken syntax @@@ !!!");
    expect(tree).toBeTruthy();
    expect(treeHasErrorNodes(tree)).toBe(true);
  });

  it("tree_error_count_valid", () => {
    // Parse valid Python code and verify zero error count
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const tree = parseString("python", "x = 1\ny = 2\n");
    expect(tree).toBeTruthy();
  });

  it("tree_find_nodes_two_functions", () => {
    // Parse Python with 2 functions and verify find_nodes_by_type count
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const tree = parseString("python", "def foo():\n    pass\n\ndef bar():\n    pass\n");
    expect(tree).toBeTruthy();
    const foundNodes = findNodesByType(tree, "function_definition");
    expect(foundNodes.length).toBeGreaterThanOrEqual(2);
  });

  it("tree_named_children_class_and_function", () => {
    // Parse Python with class and function, verify named children count
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const tree = parseString("python", "class Foo:\n    pass\n\ndef bar():\n    pass\n");
    expect(tree).toBeTruthy();
    const namedChildren = namedChildrenInfo(tree);
    expect(namedChildren.length).toBeGreaterThanOrEqual(2);
  });

  it("tree_root_node_info_python", () => {
    // Parse Python source and verify root node info
    if (!hasLanguage("python")) {
      console.log("Skipping: language 'python' not available");
      return;
    }
    const tree = parseString("python", "def hello():\n    pass\n");
    expect(tree).toBeTruthy();
    const rootInfo = rootNodeInfo(tree);
    expect(rootInfo.kind).toBe("module");
  });

});
