# Code generated by e2e-generator. DO NOT EDIT.

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import tree_sitter


def tree_contains_node_type(node: "tree_sitter.Node", node_type: str) -> bool:
    """Check whether a tree-sitter node or any descendant has the given type."""
    if node.type == node_type:
        return True
    return any(tree_contains_node_type(child, node_type) for child in node.children)


def tree_has_error_nodes(node: "tree_sitter.Node") -> bool:
    """Check whether a tree-sitter node or any descendant is an ERROR or missing node."""
    if node.type == "ERROR" or node.is_missing:
        return True
    return any(tree_has_error_nodes(child) for child in node.children)
