# Code generated by e2e-generator. DO NOT EDIT.

import pytest

from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language

from .helpers import tree_contains_node_type, tree_has_error_nodes


def test_error_handling_empty_source():
    """Parsing an empty string should still produce a tree"""
    parser = get_parser("python")
    tree = parser.parse(b"")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node


def test_error_handling_invalid_syntax():
    """Parsing invalid Python syntax should produce a tree with error nodes"""
    parser = get_parser("python")
    tree = parser.parse(b"def def def @@@ %%%")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert tree_has_error_nodes(root), "Tree should contain error nodes"


def test_error_handling_unknown_language():
    """Loading a nonexistent language should produce an error"""
    with pytest.raises(Exception):
        get_language("nonexistent_xyz")


