# Code generated by e2e-generator. DO NOT EDIT.

import pytest

from tree_sitter_language_pack import get_language, get_parser, available_languages, has_language

from .helpers import tree_contains_node_type, tree_has_error_nodes


def test_smoke_c():
    """Smoke test: load c and parse a simple snippet"""
    parser = get_parser("c")
    tree = parser.parse(b"int main() { return 0; }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_cpp():
    """Smoke test: load cpp and parse a simple snippet"""
    parser = get_parser("cpp")
    tree = parser.parse(b"int main() { return 0; }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_go():
    """Smoke test: load go and parse a simple snippet"""
    parser = get_parser("go")
    tree = parser.parse(b"package main")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_html():
    """Smoke test: load html and parse a simple snippet"""
    parser = get_parser("html")
    tree = parser.parse(b"<p>hello</p>")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_java():
    """Smoke test: load java and parse a simple snippet"""
    parser = get_parser("java")
    tree = parser.parse(b"class Main { public static void main(String[] args) {} }")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_javascript():
    """Smoke test: load javascript and parse a simple snippet"""
    parser = get_parser("javascript")
    tree = parser.parse(b"console.log('hello');")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_python():
    """Smoke test: load python and parse a simple snippet"""
    parser = get_parser("python")
    tree = parser.parse(b"print('hello')")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_ruby():
    """Smoke test: load ruby and parse a simple snippet"""
    parser = get_parser("ruby")
    tree = parser.parse(b"puts 'hello'")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_rust():
    """Smoke test: load rust and parse a simple snippet"""
    parser = get_parser("rust")
    tree = parser.parse(b"fn main() {}")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


def test_smoke_typescript():
    """Smoke test: load typescript and parse a simple snippet"""
    parser = get_parser("typescript")
    tree = parser.parse(b"const x: number = 42;")
    assert tree is not None, "Parse tree should not be None"
    root = tree.root_node
    assert root.child_count >= 1, f"Root should have at least 1 child(ren), got {root.child_count}"


