# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development do
  gem 'rake-compiler', '~> 1.2'
  gem 'rb_sys', '~> 0.9'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.60'
end
