# frozen_string_literal: true

require 'rake/extensiontask'
require 'rb_sys/extensiontask'

GEMSPEC = Gem::Specification.load('tree_sitter_language_pack.gemspec')

RbSys::ExtensionTask.new('ts-pack-ruby', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/tree_sitter_language_pack'
end

task default: :compile
