// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class MetadataTests
{

    [Fact]
    public void GoFunctionMetadata()
    {
        // Intel: extract structure from Go function definition
        if (!TsPackClient.HasLanguage("go"))
        {
            return; // Language 'go' not available
        }
        var langPtr = TsPackClient.GetLanguage("go");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void JavascriptMultiImportMetadata()
    {
        // Intel: detect multiple imports and function in JavaScript
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var langPtr = TsPackClient.GetLanguage("javascript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void MetaJavascriptExportsDetail()
    {
        // JavaScript with exports, verify export count
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var langPtr = TsPackClient.GetLanguage("javascript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void MetaPythonComments()
    {
        // Python with comments, verify comment count
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void MetaPythonImportsDetail()
    {
        // Python with multiple imports, verify imports contain specific source
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void MetaPythonMetricsDetail()
    {
        // Python code with metrics assertions
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void MetaRustStructureName()
    {
        // Rust struct with name, verify structure name contains value
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var langPtr = TsPackClient.GetLanguage("rust");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void PythonChunkingMetadata()
    {
        // Intel: chunk multi-function Python source into multiple pieces
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void PythonClassWithMethodsMetadata()
    {
        // Intel: extract nested structure from Python class with methods
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void PythonFunctionMetadata()
    {
        // Intel: extract structure from Python function definition
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void PythonMalformedCodeMetadata()
    {
        // Intel: detect diagnostics in malformed Python code
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void PythonMultiImportMetadata()
    {
        // Intel: detect multiple Python imports
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void RustChunkingMetadata()
    {
        // Intel: chunk multi-function Rust source into pieces
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var langPtr = TsPackClient.GetLanguage("rust");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void RustFunctionMetadata()
    {
        // Intel: extract structure from Rust function definition
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var langPtr = TsPackClient.GetLanguage("rust");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void TypescriptFunctionMetadata()
    {
        // Intel: extract structure from TypeScript function
        if (!TsPackClient.HasLanguage("typescript"))
        {
            return; // Language 'typescript' not available
        }
        var langPtr = TsPackClient.GetLanguage("typescript");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }
}
