// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class ProcessTests
{

    [Fact]
    public void CFunctionProcess()
    {
        // Intel: C function with include
        if (!TsPackClient.HasLanguage("c"))
        {
            return; // Language 'c' not available
        }
        var config = new ProcessConfig { Language = "c", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("#include <stdio.h>\n\nint main() {\n    printf(\"hello\");\n    return 0;\n}\n", config);
        Assert.Equal("c", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void ConfigAllPython()
    {
        // Intel: process with all features enabled
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("# A comment\ndef greet(name):\n    \"\"\"Say hello.\"\"\"\n    return f'Hi {name}'\n\nimport os\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void ConfigMinimalPython()
    {
        // Intel: process with minimal config - only metrics
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def hello():\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Metrics.TotalLines >= 2, "Should have at least 2 total line(s)");
    }

    [Fact]
    public void GoFunctionProcess()
    {
        // Intel: extract structure from Go function definition
        if (!TsPackClient.HasLanguage("go"))
        {
            return; // Language 'go' not available
        }
        var config = new ProcessConfig { Language = "go", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", config);
        Assert.Equal("go", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void GoFunctionProcessDetail()
    {
        // Intel: extract structure from Go function definition
        if (!TsPackClient.HasLanguage("go"))
        {
            return; // Language 'go' not available
        }
        var config = new ProcessConfig { Language = "go", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", config);
        Assert.Equal("go", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void JavaClassProcess()
    {
        // Intel: Java class with methods and imports
        if (!TsPackClient.HasLanguage("java"))
        {
            return; // Language 'java' not available
        }
        var config = new ProcessConfig { Language = "java", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import java.util.List;\n\npublic class Greeter {\n    public String greet(String name) {\n        return \"Hello \" + name;\n    }\n}\n", config);
        Assert.Equal("java", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Class");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void JavascriptMultiImportProcess()
    {
        // Intel: detect multiple imports and function in JavaScript
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var config = new ProcessConfig { Language = "javascript", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", config);
        Assert.Equal("javascript", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 2, "Should have at least 2 import(s)");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void JavascriptMultiImportProcessDetail()
    {
        // Intel: detect multiple imports and function in JavaScript
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var config = new ProcessConfig { Language = "javascript", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", config);
        Assert.Equal("javascript", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 2, "Should have at least 2 import(s)");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void ProcessJavascriptExportsDetail()
    {
        // JavaScript with exports, verify export count
        if (!TsPackClient.HasLanguage("javascript"))
        {
            return; // Language 'javascript' not available
        }
        var config = new ProcessConfig { Language = "javascript", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n", config);
        Assert.Equal("javascript", result.Language);
        Assert.True(result.Exports.Count >= 1, "Should have at least 1 export(s)");
    }

    [Fact]
    public void ProcessPythonComments()
    {
        // Python with comments, verify comment count
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("# This is a comment\n# Another comment\ndef hello():\n    # inline comment\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Comments.Count >= 1, "Should have at least 1 comment(s)");
    }

    [Fact]
    public void ProcessPythonImportsDetail()
    {
        // Python with multiple imports, verify imports contain specific source
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Imports.Count >= 2, "Should have at least 2 import(s)");
        Assert.Contains(result.Imports, i => i.Source.Contains("os"));
    }

    [Fact]
    public void ProcessPythonMetricsDetail()
    {
        // Python code with metrics assertions
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("# module docstring\nimport os\n\ndef hello():\n    # greeting\n    print('hello')\n\ndef world():\n    print('world')\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Metrics.CodeLines >= 4, "Should have at least 4 code line(s)");
        Assert.True(result.Metrics.CommentLines >= 1, "Should have at least 1 comment line(s)");
        Assert.True(result.Metrics.MaxDepth >= 1, "Should have max_depth >= 1");
    }

    [Fact]
    public void ProcessRustStructureName()
    {
        // Rust struct with name, verify structure name contains value
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var config = new ProcessConfig { Language = "rust", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n", config);
        Assert.Equal("rust", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Name != null && s.Name.Contains("MyConfig"));
    }

    [Fact]
    public void PythonChunkingMedium()
    {
        // Intel: Python code with medium chunk size
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", ChunkMaxSize = 50 };
        var result = TsPackClient.Process("def first():\n    x = 1\n    return x\n\ndef second():\n    y = 2\n    return y\n\ndef third():\n    z = 3\n    return z\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 3, "Should have at least 3 structure(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
        Assert.True(result.Chunks.Count >= 2, "Should have at least 2 chunk(s)");
    }

    [Fact]
    public void PythonChunkingProcessDetail()
    {
        // Intel: chunk multi-function Python source into multiple pieces
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", ChunkMaxSize = 30 };
        var result = TsPackClient.Process("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Metrics.TotalLines >= 8, "Should have at least 8 total line(s)");
        Assert.True(result.Chunks.Count >= 2, "Should have at least 2 chunk(s)");
    }

    [Fact]
    public void PythonClassWithMethodsProcess()
    {
        // Intel: extract nested structure from Python class with methods
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Class");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void PythonClassWithMethodsProcessDetail()
    {
        // Intel: extract nested structure from Python class with methods
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Class");
        Assert.True(result.Metrics.TotalLines >= 6, "Should have at least 6 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void PythonErrorDiagnostics()
    {
        // Intel: Python code with syntax errors should report diagnostics
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def broken(\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.Equal(1, result.Metrics.ErrorCount);
        Assert.NotEmpty(result.Diagnostics);
    }

    [Fact]
    public void PythonFunctionProcess()
    {
        // Intel: extract structure from Python function definition
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def greet(name):\n    return f'Hello, {name}!'\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Metrics.TotalLines >= 2, "Should have at least 2 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void PythonFunctionProcessDetail()
    {
        // Intel: extract structure from Python function definition
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def greet(name):\n    return f'Hello, {name}!'\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Metrics.TotalLines >= 2, "Should have at least 2 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void PythonMalformedCodeProcess()
    {
        // Intel: detect diagnostics in malformed Python code
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def broken(\n    return\nclass", config);
        Assert.Equal("python", result.Language);
        Assert.NotEmpty(result.Diagnostics);
    }

    [Fact]
    public void PythonMalformedCodeProcessDetail()
    {
        // Intel: detect diagnostics in malformed Python code
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("def broken(\n    return\nclass", config);
        Assert.Equal("python", result.Language);
        Assert.NotEmpty(result.Diagnostics);
    }

    [Fact]
    public void PythonMultiImportProcess()
    {
        // Intel: detect multiple Python imports
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.True(result.Imports.Count >= 3, "Should have at least 3 import(s)");
        Assert.True(result.Metrics.TotalLines >= 5, "Should have at least 5 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void PythonMultiImportProcessDetail()
    {
        // Intel: detect multiple Python imports
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var config = new ProcessConfig { Language = "python", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", config);
        Assert.Equal("python", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.True(result.Imports.Count >= 3, "Should have at least 3 import(s)");
        Assert.True(result.Metrics.TotalLines >= 5, "Should have at least 5 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void RubyClassProcess()
    {
        // Intel: Ruby class with method
        if (!TsPackClient.HasLanguage("ruby"))
        {
            return; // Language 'ruby' not available
        }
        var config = new ProcessConfig { Language = "ruby", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("require 'json'\n\nclass Greeter\n  def greet(name)\n    \"Hello #{name}\"\n  end\nend\n", config);
        Assert.Equal("ruby", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Class");
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void RustChunkingProcess()
    {
        // Intel: chunk multi-function Rust source into pieces
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var config = new ProcessConfig { Language = "rust", ChunkMaxSize = 30 };
        var result = TsPackClient.Process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", config);
        Assert.Equal("rust", result.Language);
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.True(result.Chunks.Count >= 2, "Should have at least 2 chunk(s)");
    }

    [Fact]
    public void RustChunkingProcessDetail()
    {
        // Intel: chunk multi-function Rust source into pieces
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var config = new ProcessConfig { Language = "rust", ChunkMaxSize = 30 };
        var result = TsPackClient.Process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", config);
        Assert.Equal("rust", result.Language);
        Assert.True(result.Metrics.TotalLines >= 7, "Should have at least 7 total line(s)");
        Assert.True(result.Chunks.Count >= 2, "Should have at least 2 chunk(s)");
    }

    [Fact]
    public void RustFunctionProcess()
    {
        // Intel: extract structure from Rust function definition
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var config = new ProcessConfig { Language = "rust", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", config);
        Assert.Equal("rust", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Metrics.TotalLines >= 3, "Should have at least 3 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void RustFunctionProcessDetail()
    {
        // Intel: extract structure from Rust function definition
        if (!TsPackClient.HasLanguage("rust"))
        {
            return; // Language 'rust' not available
        }
        var config = new ProcessConfig { Language = "rust", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", config);
        Assert.Equal("rust", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Metrics.TotalLines >= 3, "Should have at least 3 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void TypescriptFunctionProcess()
    {
        // Intel: extract structure from TypeScript function
        if (!TsPackClient.HasLanguage("typescript"))
        {
            return; // Language 'typescript' not available
        }
        var config = new ProcessConfig { Language = "typescript", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", config);
        Assert.Equal("typescript", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 5, "Should have at least 5 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }

    [Fact]
    public void TypescriptFunctionProcessDetail()
    {
        // Intel: extract structure from TypeScript function
        if (!TsPackClient.HasLanguage("typescript"))
        {
            return; // Language 'typescript' not available
        }
        var config = new ProcessConfig { Language = "typescript", Structure = true, Imports = true, Exports = true, Comments = true, Docstrings = true, Symbols = true, Diagnostics = true };
        var result = TsPackClient.Process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", config);
        Assert.Equal("typescript", result.Language);
        Assert.True(result.Structure.Count >= 1, "Should have at least 1 structure(s)");
        Assert.Contains(result.Structure, s => s.Kind.ToString() == "Function");
        Assert.True(result.Imports.Count >= 1, "Should have at least 1 import(s)");
        Assert.True(result.Metrics.TotalLines >= 5, "Should have at least 5 total line(s)");
        Assert.Equal(0, result.Metrics.ErrorCount);
    }
}
