// Code generated by e2e-generator. DO NOT EDIT.

using Xunit;
using TreeSitterLanguagePack;

namespace E2E.Tests;

public class TreeInspectionTests
{

    [Fact]
    public void TreeErrorCountBroken()
    {
        // Parse broken Python code and verify error count >= 1
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void TreeErrorCountValid()
    {
        // Parse valid Python code and verify zero error count
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void TreeFindNodesTwoFunctions()
    {
        // Parse Python with 2 functions and verify find_nodes_by_type count
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void TreeNamedChildrenClassAndFunction()
    {
        // Parse Python with class and function, verify named children count
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }

    [Fact]
    public void TreeRootNodeInfoPython()
    {
        // Parse Python source and verify root node info
        if (!TsPackClient.HasLanguage("python"))
        {
            return; // Language 'python' not available
        }
        var langPtr = TsPackClient.GetLanguage("python");
        Assert.True(langPtr != IntPtr.Zero, "Language pointer should not be null");
    }
}
