// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
} from "./helpers";

describe("parsing", () => {
  it("parsing_html_element", () => {
    // Parse an HTML element and assert node type
    const tree = parseString("html", `<div>hello</div>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeContainsNodeType(tree, "element")).toBe(true);
    freeTree(tree);
  });

  it("parsing_javascript_variable", () => {
    // Parse a JavaScript variable declaration and assert node type
    const tree = parseString("javascript", `const x = 1;`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeContainsNodeType(tree, "lexical_declaration")).toBe(true);
    freeTree(tree);
  });

});
