// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
  process,
  detectLanguageFromExtension,
  detectLanguageFromPath,
  detectLanguageFromContent,
  extensionAmbiguity,
  getHighlightsQuery,
} from "./helpers";

describe("process", () => {
  it("javascript_multi_import_process", () => {
    // Intel: detect multiple imports and function in JavaScript
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const intel = process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", { language: "javascript", structure: true, imports: true, exports: true, comments: true, docstrings: true, symbols: true, diagnostics: true });
    expect(intel.language).toBe("javascript");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "Function")).toBe(true);
    expect((intel.imports || []).length).toBeGreaterThanOrEqual(2);
    expect((intel.metrics || {}).totalLines || 0).toBeGreaterThanOrEqual(6);
    expect((intel.metrics || {}).errorCount || 0).toBe(0);
  });

  it("javascript_multi_import_process_detail", () => {
    // Intel: detect multiple imports and function in JavaScript
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const intel = process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", { language: "javascript", structure: true, imports: true, exports: true, comments: true, docstrings: true, symbols: true, diagnostics: true });
    expect(intel.language).toBe("javascript");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "Function")).toBe(true);
    expect((intel.imports || []).length).toBeGreaterThanOrEqual(2);
    expect((intel.metrics || {}).totalLines || 0).toBeGreaterThanOrEqual(6);
    expect((intel.metrics || {}).errorCount || 0).toBe(0);
  });

  it("process_javascript_exports_detail", () => {
    // JavaScript with exports, verify export count
    if (!hasLanguage("javascript")) {
      console.log("Skipping: language 'javascript' not available");
      return;
    }
    const intel = process("export function greet(name) {\n  return \`Hello \${name}\`;\n}\n\nexport const VERSION = '1.0';\n", { language: "javascript", structure: true, imports: true, exports: true, comments: true, docstrings: true, symbols: true, diagnostics: true });
    expect(intel.language).toBe("javascript");
    expect((intel.exports || []).length).toBeGreaterThanOrEqual(1);
  });

  it("typescript_function_process", () => {
    // Intel: extract structure from TypeScript function
    if (!hasLanguage("typescript")) {
      console.log("Skipping: language 'typescript' not available");
      return;
    }
    const intel = process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return \`Hello, \${name}!\`;\n}\n", { language: "typescript", structure: true, imports: true, exports: true, comments: true, docstrings: true, symbols: true, diagnostics: true });
    expect(intel.language).toBe("typescript");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "Function")).toBe(true);
    expect((intel.imports || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.metrics || {}).totalLines || 0).toBeGreaterThanOrEqual(5);
    expect((intel.metrics || {}).errorCount || 0).toBe(0);
  });

  it("typescript_function_process_detail", () => {
    // Intel: extract structure from TypeScript function
    if (!hasLanguage("typescript")) {
      console.log("Skipping: language 'typescript' not available");
      return;
    }
    const intel = process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return \`Hello, \${name}!\`;\n}\n", { language: "typescript", structure: true, imports: true, exports: true, comments: true, docstrings: true, symbols: true, diagnostics: true });
    expect(intel.language).toBe("typescript");
    expect((intel.structure || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.structure || []).some((s: any) => s.kind === "Function")).toBe(true);
    expect((intel.imports || []).length).toBeGreaterThanOrEqual(1);
    expect((intel.metrics || {}).totalLines || 0).toBeGreaterThanOrEqual(5);
    expect((intel.metrics || {}).errorCount || 0).toBe(0);
  });

});
