// Code generated by e2e-generator. DO NOT EDIT.

import { describe, it, expect } from "vitest";
import {
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
} from "./helpers";

describe("smoke", () => {
  it("smoke_html", () => {
    // Smoke test: load html and parse a simple snippet
    const tree = parseString("html", `<p>hello</p>`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_javascript", () => {
    // Smoke test: load javascript and parse a simple snippet
    const tree = parseString("javascript", `console.log('hello');`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

  it("smoke_typescript", () => {
    // Smoke test: load typescript and parse a simple snippet
    const tree = parseString("typescript", `const x: number = 42;`);
    expect(tree).toBeTruthy();
    expect(tree).not.toBeNull();
    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual(1);
    freeTree(tree);
  });

});
