# frozen_string_literal: true

# Code generated by e2e-generator. DO NOT EDIT.

require_relative 'spec_helper'

RSpec.describe 'metadata' do
  it 'go_function_metadata' do
    # Intel: extract structure from Go function definition
    skip "Language 'go' not available" unless TreeSitterLanguagePack.has_language('go')
    metadata = TreeSitterLanguagePack.analyze(
      "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", 'go'
    )
    expect(metadata['language']).to eq('go')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Function' }).to be true
    expect(metadata['imports'].length).to be >= 1
    expect(metadata['metrics']['total_lines']).to be >= 7
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'javascript_multi_import_metadata' do
    # Intel: detect multiple imports and function in JavaScript
    skip "Language 'javascript' not available" unless TreeSitterLanguagePack.has_language('javascript')
    metadata = TreeSitterLanguagePack.analyze(
      "import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", 'javascript'
    )
    expect(metadata['language']).to eq('javascript')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Function' }).to be true
    expect(metadata['imports'].length).to be >= 2
    expect(metadata['metrics']['total_lines']).to be >= 6
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'meta_javascript_exports_detail' do
    # JavaScript with exports, verify export count
    skip "Language 'javascript' not available" unless TreeSitterLanguagePack.has_language('javascript')
    metadata = TreeSitterLanguagePack.analyze(
      "export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n", 'javascript'
    )
    expect(metadata['language']).to eq('javascript')
    expect(metadata['exports'].length).to be >= 1
  end

  it 'meta_python_comments' do
    # Python with comments, verify comment count
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze(
      "\# This is a comment\n\# Another comment\ndef hello():\n    \# inline comment\n    pass\n", 'python'
    )
    expect(metadata['language']).to eq('python')
    expect(metadata['comments'].length).to be >= 1
  end

  it 'meta_python_imports_detail' do
    # Python with multiple imports, verify imports contain specific source
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze(
      "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", 'python'
    )
    expect(metadata['language']).to eq('python')
    expect(metadata['imports'].length).to be >= 2
    expect(metadata['imports'].any? { |i| (i['source'] || '').include?('os') }).to be true
  end

  it 'meta_python_metrics_detail' do
    # Python code with metrics assertions
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze(
      "\# module docstring\nimport os\n\ndef hello():\n    \# greeting\n    print('hello')\n\ndef world():\n    print('world')\n", 'python'
    )
    expect(metadata['language']).to eq('python')
    expect(metadata['metrics']['code_lines']).to be >= 4
    expect(metadata['metrics']['comment_lines']).to be >= 1
    expect(metadata['metrics']['max_depth']).to be >= 1
  end

  it 'meta_rust_structure_name' do
    # Rust struct with name, verify structure name contains value
    skip "Language 'rust' not available" unless TreeSitterLanguagePack.has_language('rust')
    metadata = TreeSitterLanguagePack.analyze(
      "pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n", 'rust'
    )
    expect(metadata['language']).to eq('rust')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['name']&.include?('MyConfig') }).to be true
  end

  it 'python_chunking_metadata' do
    # Intel: chunk multi-function Python source into multiple pieces
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    result = TreeSitterLanguagePack.process(
      "def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", 'python', 30
    )
    metadata = result['metadata']
    chunks = result['chunks']
    expect(metadata['language']).to eq('python')
    expect(metadata['metrics']['total_lines']).to be >= 8
    expect(chunks.length).to be >= 2
  end

  it 'python_class_with_methods_metadata' do
    # Intel: extract nested structure from Python class with methods
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze(
      "class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", 'python'
    )
    expect(metadata['language']).to eq('python')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Class' }).to be true
    expect(metadata['metrics']['total_lines']).to be >= 6
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'python_function_metadata' do
    # Intel: extract structure from Python function definition
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze("def greet(name):\n    return f'Hello, {name}!'\n", 'python')
    expect(metadata['language']).to eq('python')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Function' }).to be true
    expect(metadata['metrics']['total_lines']).to be >= 2
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'python_malformed_code_metadata' do
    # Intel: detect diagnostics in malformed Python code
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze("def broken(\n    return\nclass", 'python')
    expect(metadata['language']).to eq('python')
    expect(metadata['diagnostics']).not_to be_empty
  end

  it 'python_multi_import_metadata' do
    # Intel: detect multiple Python imports
    skip "Language 'python' not available" unless TreeSitterLanguagePack.has_language('python')
    metadata = TreeSitterLanguagePack.analyze(
      "import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", 'python'
    )
    expect(metadata['language']).to eq('python')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['imports'].length).to be >= 3
    expect(metadata['metrics']['total_lines']).to be >= 5
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'rust_chunking_metadata' do
    # Intel: chunk multi-function Rust source into pieces
    skip "Language 'rust' not available" unless TreeSitterLanguagePack.has_language('rust')
    result = TreeSitterLanguagePack.process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n",
                                            'rust', 30)
    metadata = result['metadata']
    chunks = result['chunks']
    expect(metadata['language']).to eq('rust')
    expect(metadata['metrics']['total_lines']).to be >= 7
    expect(chunks.length).to be >= 2
  end

  it 'rust_function_metadata' do
    # Intel: extract structure from Rust function definition
    skip "Language 'rust' not available" unless TreeSitterLanguagePack.has_language('rust')
    metadata = TreeSitterLanguagePack.analyze("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", 'rust')
    expect(metadata['language']).to eq('rust')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Function' }).to be true
    expect(metadata['metrics']['total_lines']).to be >= 3
    expect(metadata['metrics']['error_count']).to eq(0)
  end

  it 'typescript_function_metadata' do
    # Intel: extract structure from TypeScript function
    skip "Language 'typescript' not available" unless TreeSitterLanguagePack.has_language('typescript')
    metadata = TreeSitterLanguagePack.analyze(
      "import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", 'typescript'
    )
    expect(metadata['language']).to eq('typescript')
    expect(metadata['structure'].length).to be >= 1
    expect(metadata['structure'].any? { |s| s['kind'] == 'Function' }).to be true
    expect(metadata['imports'].length).to be >= 1
    expect(metadata['metrics']['total_lines']).to be >= 5
    expect(metadata['metrics']['error_count']).to eq(0)
  end
end
