# Code generated by e2e-generator. DO NOT EDIT.

require_relative "spec_helper"

RSpec.describe "parsing" do

  it "parsing_go_function" do
    # Parse a Go function declaration and assert node type
    tree = TreeSitterLanguagePack.parse_string("go", "package main\nfunc main() {}")
    expect(tree).not_to be_nil
    expect(tree.contains_node_type("function_declaration")).to be true
  end

  it "parsing_html_element" do
    # Parse an HTML element and assert node type
    tree = TreeSitterLanguagePack.parse_string("html", "<div>hello</div>")
    expect(tree).not_to be_nil
    expect(tree.contains_node_type("element")).to be true
  end

  it "parsing_javascript_variable" do
    # Parse a JavaScript variable declaration and assert node type
    tree = TreeSitterLanguagePack.parse_string("javascript", "const x = 1;")
    expect(tree).not_to be_nil
    expect(tree.contains_node_type("lexical_declaration")).to be true
  end

  it "parsing_python_function" do
    # Parse a Python function definition and assert node type
    tree = TreeSitterLanguagePack.parse_string("python", "def hello(): pass")
    expect(tree).not_to be_nil
    expect(tree.contains_node_type("function_definition")).to be true
  end

  it "parsing_rust_function" do
    # Parse a Rust function definition and assert node type
    tree = TreeSitterLanguagePack.parse_string("rust", "fn main() {}")
    expect(tree).not_to be_nil
    expect(tree.contains_node_type("function_item")).to be true
  end
end
