# Code generated by e2e-generator. DO NOT EDIT.

require_relative "spec_helper"

RSpec.describe "smoke" do

  it "smoke_c" do
    # Smoke test: load c and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("c", "int main() { return 0; }")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_cpp" do
    # Smoke test: load cpp and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("cpp", "int main() { return 0; }")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_go" do
    # Smoke test: load go and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("go", "package main")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_html" do
    # Smoke test: load html and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("html", "<p>hello</p>")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_java" do
    # Smoke test: load java and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("java", "class Main { public static void main(String[] args) {} }")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_javascript" do
    # Smoke test: load javascript and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("javascript", "console.log('hello');")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_python" do
    # Smoke test: load python and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("python", "print('hello')")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_ruby" do
    # Smoke test: load ruby and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("ruby", "puts 'hello'")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_rust" do
    # Smoke test: load rust and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("rust", "fn main() {}")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end

  it "smoke_typescript" do
    # Smoke test: load typescript and parse a simple snippet
    tree = TreeSitterLanguagePack.parse_string("typescript", "const x: number = 42;")
    expect(tree).not_to be_nil
    expect(tree.root_child_count).to be >= 1
  end
end
