/* Code generated by e2e-generator. DO NOT EDIT. */

#ifndef E2E_HELPERS_H
#define E2E_HELPERS_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ts_pack.h"

#define ASSERT_TRUE(expr, msg) \
    do { \
        if (!(expr)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_FALSE(expr, msg) \
    do { \
        if ((expr)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_NOT_NULL(ptr, msg) \
    do { \
        if ((ptr) == NULL) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_NULL(ptr, msg) \
    do { \
        if ((ptr) != NULL) { \
            fprintf(stderr, "FAIL: %s (line %d): %s\n", __func__, __LINE__, (msg)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_GT(a, b, msg) \
    do { \
        if (!((a) > (b))) { \
            fprintf(stderr, "FAIL: %s (line %d): %s (got %zu <= %zu)\n", __func__, __LINE__, (msg), (size_t)(a), (size_t)(b)); \
            exit(1); \
        } \
    } while (0)

#define ASSERT_EQ_BOOL(a, b, msg) \
    do { \
        if ((a) != (b)) { \
            fprintf(stderr, "FAIL: %s (line %d): %s (got %d, want %d)\n", __func__, __LINE__, (msg), (int)(a), (int)(b)); \
            exit(1); \
        } \
    } while (0)

#define TEST_PASS() \
    printf("PASS: %s\n", __func__)

#endif /* E2E_HELPERS_H */
