/* Code generated by e2e-generator. DO NOT EDIT. */

#include "helpers.h"

static void test_registry_has_language_false(void) {
    /* has_language('nonexistent') should return false */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    bool result = ts_pack_has_language(reg, "nonexistent");
    ASSERT_EQ_BOOL(result, false, "has_language check");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_registry_has_language_true(void) {
    /* has_language('python') should return true */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    bool result = ts_pack_has_language(reg, "python");
    ASSERT_EQ_BOOL(result, true, "has_language check");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_registry_list_languages(void) {
    /* available_languages should return a non-empty list */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    uintptr_t count = ts_pack_language_count(reg);
    ASSERT_GT(count, 0, "language_count should be > 0");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

int main(void) {
    test_registry_has_language_false();
    test_registry_has_language_true();
    test_registry_list_languages();
    return 0;
}
