/* Code generated by e2e-generator. DO NOT EDIT. */

#include "helpers.h"

static void test_parsing_go_function(void) {
    /* Parse a Go function declaration and assert node type */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "go");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_parsing_html_element(void) {
    /* Parse an HTML element and assert node type */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "html");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_parsing_javascript_variable(void) {
    /* Parse a JavaScript variable declaration and assert node type */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "javascript");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_parsing_python_function(void) {
    /* Parse a Python function definition and assert node type */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "python");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_parsing_rust_function(void) {
    /* Parse a Rust function definition and assert node type */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "rust");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

int main(void) {
    test_parsing_go_function();
    test_parsing_html_element();
    test_parsing_javascript_variable();
    test_parsing_python_function();
    test_parsing_rust_function();
    return 0;
}
