/* Code generated by e2e-generator. DO NOT EDIT. */

#include "helpers.h"

static void test_error_handling_empty_source(void) {
    /* Parsing an empty string should still produce a tree */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "python");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_error_handling_invalid_syntax(void) {
    /* Parsing invalid Python syntax should produce a tree with error nodes */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "python");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_error_handling_unknown_language(void) {
    /* Loading a nonexistent language should produce an error */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "nonexistent_xyz");
    ASSERT_NULL(lang, "Expected NULL for unknown language");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

int main(void) {
    test_error_handling_empty_source();
    test_error_handling_invalid_syntax();
    test_error_handling_unknown_language();
    return 0;
}
