/* Code generated by e2e-generator. DO NOT EDIT. */

#include "helpers.h"

static void test_smoke_c(void) {
    /* Smoke test: load c and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "c");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_cpp(void) {
    /* Smoke test: load cpp and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "cpp");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_go(void) {
    /* Smoke test: load go and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "go");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_html(void) {
    /* Smoke test: load html and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "html");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_java(void) {
    /* Smoke test: load java and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "java");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_javascript(void) {
    /* Smoke test: load javascript and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "javascript");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_python(void) {
    /* Smoke test: load python and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "python");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_ruby(void) {
    /* Smoke test: load ruby and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "ruby");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_rust(void) {
    /* Smoke test: load rust and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "rust");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

static void test_smoke_typescript(void) {
    /* Smoke test: load typescript and parse a simple snippet */
    TsPackRegistry *reg = ts_pack_registry_new();
    ASSERT_NOT_NULL(reg, "Failed to create registry");
    const TSLanguage *lang = ts_pack_get_language(reg, "typescript");
    ASSERT_NOT_NULL(lang, "Language pointer should not be NULL");
    ts_pack_registry_free(reg);
    TEST_PASS();
}

int main(void) {
    test_smoke_c();
    test_smoke_cpp();
    test_smoke_go();
    test_smoke_html();
    test_smoke_java();
    test_smoke_javascript();
    test_smoke_python();
    test_smoke_ruby();
    test_smoke_rust();
    test_smoke_typescript();
    return 0;
}
