use crate::fixtures::{Fixture, escape_ruby_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

pub struct RubyGenerator;

impl Generator for RubyGenerator {
    fn name(&self) -> &'static str {
        "Ruby"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let rb_dir = output_dir.join("ruby");
        std::fs::create_dir_all(rb_dir.join("spec")).map_err(|e| format!("Failed to create ruby output dir: {e}"))?;

        write_gemfile(&rb_dir)?;
        write_spec_helper(&rb_dir)?;

        let groups = group_by_category(fixtures);
        for (category, cat_fixtures) in &groups {
            write_spec_file(&rb_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_gemfile(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

source "https://rubygems.org"

gem "tree_sitter_language_pack", path: "../../crates/ts-pack-ruby"
gem "rspec", "~> 3.12"
"#;
    std::fs::write(dir.join("Gemfile"), content).map_err(|e| format!("Failed to write Gemfile: {e}"))
}

fn write_spec_helper(dir: &Path) -> Result<(), String> {
    let content = r#"# Code generated by e2e-generator. DO NOT EDIT.

require "tree_sitter_language_pack"
"#;
    std::fs::write(dir.join("spec").join("spec_helper.rb"), content)
        .map_err(|e| format!("Failed to write spec_helper.rb: {e}"))
}

fn write_spec_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();

    writeln!(out, "# Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "require_relative \"spec_helper\"").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "RSpec.describe \"{}\" do", category).unwrap();

    for fixture in fixtures {
        let test_name = sanitize_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        // Skip logic
        let has_skip = fixture.skip.as_ref().is_some_and(|s| s.requires_language.is_some());

        writeln!(out).unwrap();
        writeln!(out, "  it \"{}\" do", test_name).unwrap();
        writeln!(out, "    # {}", fixture.description).unwrap();

        if has_skip {
            let req_lang = fixture.skip.as_ref().unwrap().requires_language.as_ref().unwrap();
            writeln!(
                out,
                "    skip \"Language '{}' not available\" unless TreeSitterLanguagePack.has_language(\"{}\")",
                escape_ruby_string(req_lang),
                escape_ruby_string(req_lang)
            )
            .unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(
                    out,
                    "    expect {{ TreeSitterLanguagePack.get_language_ptr(\"{}\") }}.to raise_error(RuntimeError)",
                    escape_ruby_string(lang)
                )
                .unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "    langs = TreeSitterLanguagePack.available_languages").unwrap();
            writeln!(out, "    expect(langs).not_to be_empty").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "    expect(TreeSitterLanguagePack.has_language(\"{}\")).to eq({})",
                escape_ruby_string(lang),
                expected
            )
            .unwrap();
        } else if let Some(lang) = &fixture.language {
            let source = fixture.source_code.as_deref().unwrap_or("");
            // Use parse_string which returns a TreeWrapper
            writeln!(
                out,
                "    tree = TreeSitterLanguagePack.parse_string(\"{}\", \"{}\")",
                escape_ruby_string(lang),
                escape_ruby_string(source)
            )
            .unwrap();

            if assertions.is_some_and(|a| a.tree_not_null == Some(true)) {
                writeln!(out, "    expect(tree).not_to be_nil").unwrap();

                if let Some(min_children) = assertions.and_then(|a| a.root_child_count_min) {
                    writeln!(out, "    expect(tree.root_child_count).to be >= {}", min_children).unwrap();
                }

                if let Some(node_type) = assertions.and_then(|a| a.root_contains_node_type.as_deref()) {
                    writeln!(
                        out,
                        "    expect(tree.contains_node_type(\"{}\")).to be true",
                        escape_ruby_string(node_type)
                    )
                    .unwrap();
                }

                if assertions.is_some_and(|a| a.has_error_nodes == Some(true)) {
                    writeln!(out, "    expect(tree.has_error_nodes).to be true").unwrap();
                }
            } else {
                // Default: just verify parse succeeds
                writeln!(out, "    expect(tree).not_to be_nil").unwrap();
            }
        }

        writeln!(out, "  end").unwrap();
    }

    writeln!(out, "end").unwrap();

    let filename = format!("{}_spec.rb", sanitize_name(category));
    std::fs::write(dir.join("spec").join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}
