use crate::fixtures::{Fixture, escape_js_string, group_by_category, sanitize_name};
use crate::generators::Generator;
use std::fmt::Write as FmtWrite;
use std::path::Path;

/// Languages available in the WASM build (matches ts-pack-core "web" feature group).
const WEB_LANGUAGES: &[&str] = &[
    "html",
    "css",
    "javascript",
    "typescript",
    "tsx",
    "json",
    "vue",
    "svelte",
    "astro",
    "graphql",
    "scss",
    "jsdoc",
    "twig",
    "prisma",
];

pub struct WasmGenerator;

impl Generator for WasmGenerator {
    fn name(&self) -> &'static str {
        "WebAssembly"
    }

    fn generate(&self, fixtures: &[Fixture], output_dir: &Path) -> Result<(), String> {
        let wasm_dir = output_dir.join("wasm");
        let tests_dir = wasm_dir.join("tests");

        // Clean old generated test files before writing new ones
        if tests_dir.exists() {
            for entry in std::fs::read_dir(&tests_dir).map_err(|e| format!("Failed to read tests dir: {e}"))? {
                let entry = entry.map_err(|e| format!("Failed to read dir entry: {e}"))?;
                let path = entry.path();
                if path.extension().is_some_and(|ext| ext == "ts") {
                    std::fs::remove_file(&path).map_err(|e| format!("Failed to remove {}: {e}", path.display()))?;
                }
            }
        }

        std::fs::create_dir_all(&tests_dir).map_err(|e| format!("Failed to create wasm output dir: {e}"))?;

        write_package_json(&wasm_dir)?;
        write_helpers_ts(&wasm_dir)?;

        // Filter fixtures to only languages available in the WASM web build
        let filtered: Vec<&Fixture> = fixtures
            .iter()
            .filter(|f| {
                // Keep fixtures that test error paths (expect_error) regardless of language
                if f.assertions.as_ref().is_some_and(|a| a.expect_error == Some(true)) {
                    return true;
                }
                // Otherwise filter to web-available languages only
                f.language
                    .as_ref()
                    .map(|lang| WEB_LANGUAGES.contains(&lang.as_str()))
                    .unwrap_or(true)
            })
            .collect();

        let owned: Vec<Fixture> = filtered.into_iter().cloned().collect();
        let groups = group_by_category(&owned);
        for (category, cat_fixtures) in &groups {
            write_test_file(&wasm_dir, category, cat_fixtures)?;
        }

        Ok(())
    }
}

fn write_package_json(dir: &Path) -> Result<(), String> {
    let content = r#"{
  "name": "e2e-wasm-tests",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "test": "vitest run"
  },
  "dependencies": {
    "@kreuzberg/tree-sitter-language-pack-wasm": "file:../../crates/ts-pack-wasm/pkg"
  },
  "devDependencies": {
    "vitest": "^3.0.0"
  }
}
"#;
    std::fs::write(dir.join("package.json"), content).map_err(|e| format!("Failed to write package.json: {e}"))
}

fn write_helpers_ts(dir: &Path) -> Result<(), String> {
    let content = r#"// Code generated by e2e-generator. DO NOT EDIT.

// The nodejs wasm-pack target auto-initializes the WASM module on first require,
// so we simply re-export the functions — no manual init needed.
export {
  availableLanguages,
  hasLanguage,
  languageCount,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
} from "@kreuzberg/tree-sitter-language-pack-wasm";
"#;
    std::fs::write(dir.join("tests").join("helpers.ts"), content)
        .map_err(|e| format!("Failed to write helpers.ts: {e}"))
}

fn write_test_file(dir: &Path, category: &str, fixtures: &[&Fixture]) -> Result<(), String> {
    let mut out = String::new();

    writeln!(out, "// Code generated by e2e-generator. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import {{ describe, it, expect }} from \"vitest\";").unwrap();
    writeln!(
        out,
        "import {{
  availableLanguages,
  hasLanguage,
  getLanguagePtr,
  parseString,
  treeRootNodeType,
  treeRootChildCount,
  treeContainsNodeType,
  treeHasErrorNodes,
  freeTree,
}} from \"./helpers\";"
    )
    .unwrap();
    writeln!(out).unwrap();

    let cat_name = sanitize_name(category);
    writeln!(out, "describe(\"{cat_name}\", () => {{").unwrap();

    for fixture in fixtures {
        let test_name = sanitize_name(&fixture.id);
        let assertions = fixture.assertions.as_ref();

        writeln!(out, "  it(\"{test_name}\", () => {{").unwrap();
        writeln!(out, "    // {}", fixture.description).unwrap();

        // Skip logic
        if let Some(skip) = &fixture.skip
            && let Some(req_lang) = &skip.requires_language
        {
            writeln!(out, "    if (!hasLanguage(\"{req_lang}\")) {{").unwrap();
            writeln!(
                out,
                "      console.log(\"Skipping: language '{}' not available\");",
                req_lang
            )
            .unwrap();
            writeln!(out, "      return;").unwrap();
            writeln!(out, "    }}").unwrap();
        }

        if assertions.is_some_and(|a| a.expect_error == Some(true)) {
            if let Some(lang) = &fixture.language {
                writeln!(
                    out,
                    "    expect(() => getLanguagePtr(\"{}\")).toThrow();",
                    escape_js_string(lang)
                )
                .unwrap();
            }
        } else if assertions.is_some_and(|a| a.languages_not_empty == Some(true)) {
            writeln!(out, "    const langs = availableLanguages();").unwrap();
            writeln!(out, "    expect(langs.length).toBeGreaterThan(0);").unwrap();
        } else if assertions.is_some_and(|a| a.language_available.is_some()) {
            let expected = assertions.unwrap().language_available.unwrap();
            let lang = fixture.language.as_deref().unwrap_or("unknown");
            writeln!(
                out,
                "    expect(hasLanguage(\"{}\")).toBe({});",
                escape_js_string(lang),
                expected
            )
            .unwrap();
        } else if let Some(lang) = &fixture.language {
            // WASM has full parse API — use parseString + tree inspection
            writeln!(
                out,
                "    const tree = parseString(\"{}\", `{}`);",
                escape_js_string(lang),
                escape_js_string(fixture.source_code.as_deref().unwrap_or(""))
            )
            .unwrap();
            writeln!(out, "    expect(tree).toBeTruthy();").unwrap();

            if let Some(a) = assertions {
                if a.tree_not_null == Some(true) {
                    writeln!(out, "    expect(tree).not.toBeNull();").unwrap();
                }
                if let Some(min_count) = a.root_child_count_min {
                    writeln!(
                        out,
                        "    expect(treeRootChildCount(tree)).toBeGreaterThanOrEqual({min_count});"
                    )
                    .unwrap();
                }
                if let Some(node_type) = &a.root_contains_node_type {
                    writeln!(
                        out,
                        "    expect(treeContainsNodeType(tree, \"{}\")).toBe(true);",
                        escape_js_string(node_type)
                    )
                    .unwrap();
                }
                if let Some(has_errors) = a.has_error_nodes {
                    writeln!(out, "    expect(treeHasErrorNodes(tree)).toBe({has_errors});").unwrap();
                }
            }

            writeln!(out, "    freeTree(tree);").unwrap();
        }

        writeln!(out, "  }});").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "}});").unwrap();

    let filename = format!("{}.spec.ts", sanitize_name(category));
    std::fs::write(dir.join("tests").join(&filename), &out).map_err(|e| format!("Failed to write {filename}: {e}"))
}
