// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import (
	"strings"
	"testing"

	tspack "github.com/kreuzberg-dev/tree-sitter-language-pack/packages/go"
)

func TestCFunctionProcess(t *testing.T) {
	// Intel: C function with include
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "c")
	result, err := reg.Process("#include <stdio.h>\n\nint main() {\n    printf(\"hello\");\n    return 0;\n}\n", tspack.ProcessConfig{Language: "c", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "c" {
		t.Fatalf("expected language %q, got %q", "c", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestConfigAllPython(t *testing.T) {
	// Intel: process with all features enabled
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("# A comment\ndef greet(name):\n    \"\"\"Say hello.\"\"\"\n    return f'Hi {name}'\n\nimport os\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestConfigMinimalPython(t *testing.T) {
	// Intel: process with minimal config - only metrics
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def hello():\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if result.Metrics.TotalLines < 2 {
		t.Fatalf("expected at least 2 total line(s), got %d", result.Metrics.TotalLines)
	}
}

func TestGoFunctionProcess(t *testing.T) {
	// Intel: extract structure from Go function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "go")
	result, err := reg.Process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", tspack.ProcessConfig{Language: "go", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "go" {
		t.Fatalf("expected language %q, got %q", "go", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestGoFunctionProcessDetail(t *testing.T) {
	// Intel: extract structure from Go function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "go")
	result, err := reg.Process("package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n", tspack.ProcessConfig{Language: "go", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "go" {
		t.Fatalf("expected language %q, got %q", "go", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestJavaClassProcess(t *testing.T) {
	// Intel: Java class with methods and imports
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "java")
	result, err := reg.Process("import java.util.List;\n\npublic class Greeter {\n    public String greet(String name) {\n        return \"Hello \" + name;\n    }\n}\n", tspack.ProcessConfig{Language: "java", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "java" {
		t.Fatalf("expected language %q, got %q", "java", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Class" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Class' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestJavascriptMultiImportProcess(t *testing.T) {
	// Intel: detect multiple imports and function in JavaScript
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	result, err := reg.Process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", tspack.ProcessConfig{Language: "javascript", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "javascript" {
		t.Fatalf("expected language %q, got %q", "javascript", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 2 {
		t.Fatalf("expected at least 2 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestJavascriptMultiImportProcessDetail(t *testing.T) {
	// Intel: detect multiple imports and function in JavaScript
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	result, err := reg.Process("import fs from 'fs';\nimport path from 'path';\n\nfunction process(input) {\n    return input.trim();\n}\n", tspack.ProcessConfig{Language: "javascript", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "javascript" {
		t.Fatalf("expected language %q, got %q", "javascript", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 2 {
		t.Fatalf("expected at least 2 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestProcessJavascriptExportsDetail(t *testing.T) {
	// JavaScript with exports, verify export count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "javascript")
	result, err := reg.Process("export function greet(name) {\n  return `Hello ${name}`;\n}\n\nexport const VERSION = '1.0';\n", tspack.ProcessConfig{Language: "javascript", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "javascript" {
		t.Fatalf("expected language %q, got %q", "javascript", result.Language)
	}

	if len(result.Exports) < 1 {
		t.Fatalf("expected at least 1 export(s), got %d", len(result.Exports))
	}
}

func TestProcessPythonComments(t *testing.T) {
	// Python with comments, verify comment count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("# This is a comment\n# Another comment\ndef hello():\n    # inline comment\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Comments) < 1 {
		t.Fatalf("expected at least 1 comment(s), got %d", len(result.Comments))
	}
}

func TestProcessPythonImportsDetail(t *testing.T) {
	// Python with multiple imports, verify imports contain specific source
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Imports) < 2 {
		t.Fatalf("expected at least 2 import(s), got %d", len(result.Imports))
	}

	foundImport := false
	for _, imp := range result.Imports {
		if strings.Contains(imp.Source, "os") {
			foundImport = true
			break
		}
	}
	if !foundImport {
		t.Fatal("imports should contain source 'os'")
	}
}

func TestProcessPythonMetricsDetail(t *testing.T) {
	// Python code with metrics assertions
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("# module docstring\nimport os\n\ndef hello():\n    # greeting\n    print('hello')\n\ndef world():\n    print('world')\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if result.Metrics.CodeLines < 4 {
		t.Fatalf("expected at least 4 code line(s), got %d", result.Metrics.CodeLines)
	}

	if result.Metrics.CommentLines < 1 {
		t.Fatalf("expected at least 1 comment line(s), got %d", result.Metrics.CommentLines)
	}

	if result.Metrics.MaxDepth < 1 {
		t.Fatalf("expected max_depth >= 1, got %d", result.Metrics.MaxDepth)
	}
}

func TestProcessRustStructureName(t *testing.T) {
	// Rust struct with name, verify structure name contains value
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	result, err := reg.Process("pub struct MyConfig {\n    pub name: String,\n    pub value: i32,\n}\n\nimpl MyConfig {\n    pub fn new() -> Self {\n        Self { name: String::new(), value: 0 }\n    }\n}\n", tspack.ProcessConfig{Language: "rust", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundName := false
	for _, s := range result.Structure {
		if s.Name != nil && strings.Contains(*s.Name, "MyConfig") {
			foundName = true
			break
		}
	}
	if !foundName {
		t.Fatal("structure should contain an item with name containing 'MyConfig'")
	}
}

func TestPythonChunkingMedium(t *testing.T) {
	// Intel: Python code with medium chunk size
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	chunkSize := 50
	result, err := reg.Process("def first():\n    x = 1\n    return x\n\ndef second():\n    y = 2\n    return y\n\ndef third():\n    z = 3\n    return z\n", tspack.ProcessConfig{Language: "python", ChunkMaxSize: &chunkSize, Structure: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if len(result.Chunks) < 2 {
		t.Fatalf("expected at least 2 chunk(s), got %d", len(result.Chunks))
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 3 {
		t.Fatalf("expected at least 3 structure(s), got %d", len(result.Structure))
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonChunkingProcessDetail(t *testing.T) {
	// Intel: chunk multi-function Python source into multiple pieces
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	chunkSize := 30
	result, err := reg.Process("def alpha():\n    pass\n\ndef beta():\n    pass\n\ndef gamma():\n    pass\n\ndef delta():\n    pass\n", tspack.ProcessConfig{Language: "python", ChunkMaxSize: &chunkSize})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if len(result.Chunks) < 2 {
		t.Fatalf("expected at least 2 chunk(s), got %d", len(result.Chunks))
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if result.Metrics.TotalLines < 8 {
		t.Fatalf("expected at least 8 total line(s), got %d", result.Metrics.TotalLines)
	}
}

func TestPythonClassWithMethodsProcess(t *testing.T) {
	// Intel: extract nested structure from Python class with methods
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Class" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Class' kind node")
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonClassWithMethodsProcessDetail(t *testing.T) {
	// Intel: extract nested structure from Python class with methods
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("class Calculator:\n    def add(self, a, b):\n        return a + b\n\n    def subtract(self, a, b):\n        return a - b\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Class" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Class' kind node")
	}

	if result.Metrics.TotalLines < 6 {
		t.Fatalf("expected at least 6 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonErrorDiagnostics(t *testing.T) {
	// Intel: Python code with syntax errors should report diagnostics
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def broken(\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if result.Metrics.ErrorCount != 1 {
		t.Fatalf("expected error_count 1, got %d", result.Metrics.ErrorCount)
	}

	if len(result.Diagnostics) == 0 {
		t.Fatal("diagnostics should not be empty")
	}
}

func TestPythonFunctionProcess(t *testing.T) {
	// Intel: extract structure from Python function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def greet(name):\n    return f'Hello, {name}!'\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if result.Metrics.TotalLines < 2 {
		t.Fatalf("expected at least 2 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonFunctionProcessDetail(t *testing.T) {
	// Intel: extract structure from Python function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def greet(name):\n    return f'Hello, {name}!'\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if result.Metrics.TotalLines < 2 {
		t.Fatalf("expected at least 2 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonMalformedCodeProcess(t *testing.T) {
	// Intel: detect diagnostics in malformed Python code
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def broken(\n    return\nclass", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Diagnostics) == 0 {
		t.Fatal("diagnostics should not be empty")
	}
}

func TestPythonMalformedCodeProcessDetail(t *testing.T) {
	// Intel: detect diagnostics in malformed Python code
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("def broken(\n    return\nclass", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Diagnostics) == 0 {
		t.Fatal("diagnostics should not be empty")
	}
}

func TestPythonMultiImportProcess(t *testing.T) {
	// Intel: detect multiple Python imports
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	if len(result.Imports) < 3 {
		t.Fatalf("expected at least 3 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 5 {
		t.Fatalf("expected at least 5 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestPythonMultiImportProcessDetail(t *testing.T) {
	// Intel: detect multiple Python imports
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	result, err := reg.Process("import os\nimport sys\nfrom pathlib import Path\n\ndef main():\n    pass\n", tspack.ProcessConfig{Language: "python", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "python" {
		t.Fatalf("expected language %q, got %q", "python", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	if len(result.Imports) < 3 {
		t.Fatalf("expected at least 3 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 5 {
		t.Fatalf("expected at least 5 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestRubyClassProcess(t *testing.T) {
	// Intel: Ruby class with method
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "ruby")
	result, err := reg.Process("require 'json'\n\nclass Greeter\n  def greet(name)\n    \"Hello #{name}\"\n  end\nend\n", tspack.ProcessConfig{Language: "ruby", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "ruby" {
		t.Fatalf("expected language %q, got %q", "ruby", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Class" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Class' kind node")
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestRustChunkingProcess(t *testing.T) {
	// Intel: chunk multi-function Rust source into pieces
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	chunkSize := 30
	result, err := reg.Process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", tspack.ProcessConfig{Language: "rust", ChunkMaxSize: &chunkSize})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if len(result.Chunks) < 2 {
		t.Fatalf("expected at least 2 chunk(s), got %d", len(result.Chunks))
	}

	if result.Language != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", result.Language)
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}
}

func TestRustChunkingProcessDetail(t *testing.T) {
	// Intel: chunk multi-function Rust source into pieces
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	chunkSize := 30
	result, err := reg.Process("fn alpha() {}\n\nfn beta() {}\n\nfn gamma() {}\n\nfn delta() {}\n", tspack.ProcessConfig{Language: "rust", ChunkMaxSize: &chunkSize})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if len(result.Chunks) < 2 {
		t.Fatalf("expected at least 2 chunk(s), got %d", len(result.Chunks))
	}

	if result.Language != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", result.Language)
	}

	if result.Metrics.TotalLines < 7 {
		t.Fatalf("expected at least 7 total line(s), got %d", result.Metrics.TotalLines)
	}
}

func TestRustFunctionProcess(t *testing.T) {
	// Intel: extract structure from Rust function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	result, err := reg.Process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", tspack.ProcessConfig{Language: "rust", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if result.Metrics.TotalLines < 3 {
		t.Fatalf("expected at least 3 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestRustFunctionProcessDetail(t *testing.T) {
	// Intel: extract structure from Rust function definition
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "rust")
	result, err := reg.Process("fn add(a: i32, b: i32) -> i32 {\n    a + b\n}\n", tspack.ProcessConfig{Language: "rust", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "rust" {
		t.Fatalf("expected language %q, got %q", "rust", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if result.Metrics.TotalLines < 3 {
		t.Fatalf("expected at least 3 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestTypescriptFunctionProcess(t *testing.T) {
	// Intel: extract structure from TypeScript function
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "typescript")
	result, err := reg.Process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", tspack.ProcessConfig{Language: "typescript", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "typescript" {
		t.Fatalf("expected language %q, got %q", "typescript", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 5 {
		t.Fatalf("expected at least 5 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}

func TestTypescriptFunctionProcessDetail(t *testing.T) {
	// Intel: extract structure from TypeScript function
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "typescript")
	result, err := reg.Process("import { readFile } from 'fs';\n\nfunction greet(name: string): string {\n    return `Hello, ${name}!`;\n}\n", tspack.ProcessConfig{Language: "typescript", Structure: true, Imports: true, Exports: true, Comments: true, Docstrings: true, Symbols: true, Diagnostics: true})
	if err != nil {
		t.Fatalf("process failed: %v", err)
	}

	if result.Language != "typescript" {
		t.Fatalf("expected language %q, got %q", "typescript", result.Language)
	}

	if len(result.Structure) < 1 {
		t.Fatalf("expected at least 1 structure(s), got %d", len(result.Structure))
	}

	foundKind := false
	for _, s := range result.Structure {
		if s.Kind == "Function" {
			foundKind = true
			break
		}
	}
	if !foundKind {
		t.Fatal("structure should contain a 'Function' kind node")
	}

	if len(result.Imports) < 1 {
		t.Fatalf("expected at least 1 import(s), got %d", len(result.Imports))
	}

	if result.Metrics.TotalLines < 5 {
		t.Fatalf("expected at least 5 total line(s), got %d", result.Metrics.TotalLines)
	}

	if result.Metrics.ErrorCount != 0 {
		t.Fatalf("expected error_count 0, got %d", result.Metrics.ErrorCount)
	}
}
