// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestSmokeC(t *testing.T) {
	// Smoke test: load c and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("c")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "c", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "c")
	}
}

func TestSmokeCpp(t *testing.T) {
	// Smoke test: load cpp and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("cpp")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "cpp", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "cpp")
	}
}

func TestSmokeGo(t *testing.T) {
	// Smoke test: load go and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("go")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "go", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "go")
	}
}

func TestSmokeHtml(t *testing.T) {
	// Smoke test: load html and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("html")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "html", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "html")
	}
}

func TestSmokeJava(t *testing.T) {
	// Smoke test: load java and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("java")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "java", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "java")
	}
}

func TestSmokeJavascript(t *testing.T) {
	// Smoke test: load javascript and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("javascript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "javascript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "javascript")
	}
}

func TestSmokePython(t *testing.T) {
	// Smoke test: load python and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("python")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "python", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "python")
	}
}

func TestSmokeRuby(t *testing.T) {
	// Smoke test: load ruby and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("ruby")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "ruby", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "ruby")
	}
}

func TestSmokeRust(t *testing.T) {
	// Smoke test: load rust and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("rust")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "rust", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "rust")
	}
}

func TestSmokeTypescript(t *testing.T) {
	// Smoke test: load typescript and parse a simple snippet
	reg := newTestRegistry(t)
	ptr, err := reg.GetLanguage("typescript")
	if err != nil {
		t.Fatalf("Failed to get language %q: %v", "typescript", err)
	}
	if ptr == nil {
		t.Fatalf("Language pointer for %q is nil", "typescript")
	}
}

