// Code generated by e2e-generator. DO NOT EDIT.

package e2e_tests

import "testing"

func TestTreeErrorCountBroken(t *testing.T) {
	// Parse broken Python code and verify error count >= 1
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	tree, err := reg.ParseString("python", "def (broken syntax @@@ !!!")
	if err != nil {
		t.Fatalf("Failed to parse language %q: %v", "python", err)
	}
	defer tree.Close()
	if tree == nil {
		t.Fatalf("Expected non-nil tree for language %q", "python")
	}
	hasErrors, err := tree.HasErrorNodes()
	if err != nil {
		t.Fatalf("HasErrorNodes failed: %v", err)
	}
	if !hasErrors {
		t.Fatal("Expected tree to have error nodes")
	}
}

func TestTreeErrorCountValid(t *testing.T) {
	// Parse valid Python code and verify zero error count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	tree, err := reg.ParseString("python", "x = 1\ny = 2\n")
	if err != nil {
		t.Fatalf("Failed to parse language %q: %v", "python", err)
	}
	defer tree.Close()

	hasErrors, err := tree.HasErrorNodes()
	if err != nil {
		t.Fatalf("HasErrorNodes failed: %v", err)
	}
	if hasErrors {
		t.Fatal("expected no error nodes")
	}
}

func TestTreeFindNodesTwoFunctions(t *testing.T) {
	// Parse Python with 2 functions and verify find_nodes_by_type count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	tree, err := reg.ParseString("python", "def foo():\n    pass\n\ndef bar():\n    pass\n")
	if err != nil {
		t.Fatalf("Failed to parse language %q: %v", "python", err)
	}
	defer tree.Close()

	nodes, err := tree.FindNodesByType("function_definition")
	if err != nil {
		t.Fatalf("FindNodesByType failed: %v", err)
	}
	if len(nodes) < 2 {
		t.Fatalf("expected >= 2 node(s) of type 'function_definition', got %d", len(nodes))
	}
}

func TestTreeNamedChildrenClassAndFunction(t *testing.T) {
	// Parse Python with class and function, verify named children count
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	tree, err := reg.ParseString("python", "class Foo:\n    pass\n\ndef bar():\n    pass\n")
	if err != nil {
		t.Fatalf("Failed to parse language %q: %v", "python", err)
	}
	defer tree.Close()

	children, err := tree.NamedChildrenInfo()
	if err != nil {
		t.Fatalf("NamedChildrenInfo failed: %v", err)
	}
	if len(children) < 2 {
		t.Fatalf("expected >= 2 named child(ren), got %d", len(children))
	}
}

func TestTreeRootNodeInfoPython(t *testing.T) {
	// Parse Python source and verify root node info
	reg := newTestRegistry(t)
	skipIfLanguageUnavailable(t, reg, "python")
	tree, err := reg.ParseString("python", "def hello():\n    pass\n")
	if err != nil {
		t.Fatalf("Failed to parse language %q: %v", "python", err)
	}
	defer tree.Close()

	rootType, err := tree.RootNodeType()
	if err != nil {
		t.Fatalf("RootNodeType failed: %v", err)
	}
	if rootType != "module" {
		t.Fatalf("expected root type %q, got %q", "module", rootType)
	}
}
